// ═══════════════════════════════════════════════════════════
// HCODE.ART • KOREAN CORE VOCABULARY (350+ WORDS WITH EMOJIS)
// Classified into 8 Themes with Decomposition & Sample Sentences
// ═══════════════════════════════════════════════════════════

window.KOREAN_VOCAB_DATA = [
  // ─── 1. LIDÉ, RODINA & PROFESE (45 slov) ───
  { hangul: "사람", roman: "saram", cz: "člověk / lidé", cat: "people", emoji: "👤", decomp: "사 [ㅅ+ㅏ] + 람 [ㄹ+ㅏ+ㅁ]", hanja: "", ex: "좋은 사람이에요. (Je to dobrý člověk.)" },
  { hangul: "친구", roman: "chingu", cz: "kamarád / přítel", cat: "people", emoji: "🤝", decomp: "친 [ㅊ+ㅣ+ㄴ] + 구 [ㄱ+ㅜ]", hanja: "親舊", ex: "제 친구를 소개합니다. (Představuji vám mého kamaráda.)" },
  { hangul: "가족", roman: "gajok", cz: "rodina", cat: "people", emoji: "👨‍👩‍👧‍👦", decomp: "가 [ㄱ+ㅏ] + 족 [ㅈ+ㅗ+ㄱ]", hanja: "家族", ex: "가족과 함께 살아요. (Žiji společně s rodinou.)" },
  { hangul: "아버지", roman: "abeoji", cz: "otec / tatínek", cat: "people", emoji: "👨", decomp: "아 [ㅇ+ㅏ] + 버 [ㅂ+ㅓ] + 지 [ㅈ+ㅣ]", hanja: "", ex: "아버지는 회사에 가셨어요. (Tatínek šel do práce.)" },
  { hangul: "어머니", roman: "eomeoni", cz: "matka / maminka", cat: "people", emoji: "👩", decomp: "어 [ㅇ+ㅓ] + 머 [ㅁ+ㅓ] + 니 [ㄴ+ㅣ]", hanja: "", ex: "어머니가 요리를 하세요. (Maminka vaří.)" },
  { hangul: "아빠", roman: "appa", cz: "táta (neformálně)", cat: "people", emoji: "👨‍👧", decomp: "아 [ㅇ+ㅏ] + 빠 [ㅃ+ㅏ]", hanja: "", ex: "아빠, 사랑해요! (Tati, mám tě rád!)" },
  { hangul: "엄마", roman: "eomma", cz: "máma (neformálně)", cat: "people", emoji: "👩‍👧", decomp: "엄 [ㅇ+ㅓ+ㅁ] + 마 [ㅁ+ㅏ]", hanja: "", ex: "엄마, 밥 주세요. (Mami, dej mi jídlo, prosím.)" },
  { hangul: "형", roman: "hyeong", cz: "starší bratr (říká muž)", cat: "people", emoji: "👦", decomp: "형 [ㅎ+ㅕ+ㅇ]", hanja: "兄", ex: "우리 형은 대학생이에요. (Můj starší bratr je vysokoškolák.)" },
  { hangul: "오빠", roman: "oppa", cz: "starší bratr (říká žena)", cat: "people", emoji: "🧑", decomp: "오 [ㅇ+ㅗ] + 빠 [ㅃ+ㅏ]", hanja: "", ex: "오빠, 어디 가요? (Oppa, kam jdeš?)" },
  { hangul: "누나", roman: "nuna", cz: "starší sestra (říká muž)", cat: "people", emoji: "👧", decomp: "누 [ㄴ+ㅜ] + 나 [ㄴ+ㅏ]", hanja: "", ex: "누나가 책을 읽어요. (Starší sestra čte knihu.)" },
  { hangul: "언니", roman: "eonni", cz: "starší sestra (říká žena)", cat: "people", emoji: "👩", decomp: "언 [ㅇ+ㅓ+ㄴ] + 니 [ㄴ+ㅣ]", hanja: "", ex: "언니랑 쇼핑했어요. (Šla jsem na nákupy se sestrou.)" },
  { hangul: "동생", roman: "dongsaeng", cz: "mladší sourozenec", cat: "people", emoji: "🧒", decomp: "동 [ㄷ+ㅗ+ㅇ] + 생 [ㅅ+ㅐ+ㅇ]", hanja: "同生", ex: "동생이 두 명 있어요. (Mám dva mladší sourozence.)" },
  { hangul: "남동생", roman: "namdongsaeng", cz: "mladší bratr", cat: "people", emoji: "👦", decomp: "남 [ㄴ+ㅏ+ㅁ] + 동 [ㄷ+ㅗ+ㅇ] + 생 [ㅅ+ㅐ+ㅇ]", hanja: "男同生", ex: "남동생은 축구를 좋아해요. (Mladší bratr má rád fotbal.)" },
  { hangul: "여동생", roman: "yeodongsaeng", cz: "mladší sestra", cat: "people", emoji: "👧", decomp: "여 [ㅇ+ㅕ] + 동 [ㄷ+ㅗ+ㅇ] + 생 [ㅅ+ㅐ+ㅇ]", hanja: "女同生", ex: "여동생이 귀여워요. (Mladší sestra je roztomilá.)" },
  { hangul: "할아버지", roman: "harabeoji", cz: "dědeček", cat: "people", emoji: "👴", decomp: "할 [ㅎ+ㅏ+ㄹ] + 아 [ㅇ+ㅏ] + 버 [ㅂ+ㅓ] + 지 [ㅈ+ㅣ]", hanja: "", ex: "할아버지, 건강하세요. (Dědečku, hodně zdraví.)" },
  { hangul: "할머니", roman: "halmeoni", cz: "babička", cat: "people", emoji: "👵", decomp: "할 [ㅎ+ㅏ+ㄹ] + 머 [ㅁ+ㅓ] + 니 [ㄴ+ㅣ]", hanja: "", ex: "할머니가 김치를 만들어 주셨어요. (Babička mi udělala kimči.)" },
  { hangul: "선생님", roman: "seonsaengnim", cz: "učitel / pan učitel", cat: "people", emoji: "🧑‍🏫", decomp: "선 [ㅅ+ㅓ+ㄴ] + 생 [ㅅ+ㅐ+ㅇ] + 님 [ㄴ+ㅣ+ㅁ]", hanja: "先生님", ex: "선생님, 질문이 있어요. (Pane učiteli, mám otázku.)" },
  { hangul: "학생", roman: "haksaeng", cz: "student / žák", cat: "people", emoji: "🧑‍🎓", decomp: "학 [ㅎ+ㅏ+ㄱ] + 생 [ㅅ+ㅐ+ㅇ]", hanja: "學生", ex: "저는 한국어 학생이에요. (Jsem student korejštiny.)" },
  { hangul: "의사", roman: "uisa", cz: "lékař / doktor", cat: "people", emoji: "👨‍⚕️", decomp: "의 [ㅇ+ㅢ] + 사 [ㅅ+ㅏ]", hanja: "醫師", ex: "의사 선생님을 만났어요. (Setkal jsem se s panem doktorem.)" },
  { hangul: "간호사", roman: "ganhosa", cz: "zdravotní sestra", cat: "people", emoji: "👩‍⚕️", decomp: "간 [ㄱ+ㅏ+ㄴ] + 호 [ㅎ+ㅗ] + 사 [ㅅ+ㅏ]", hanja: "看護師", ex: "간호사가 친절해요. (Zdravotní sestra je milá.)" },
  { hangul: "회사원", roman: "hoesawon", cz: "kancelářský pracovník", cat: "people", emoji: "💼", decomp: "회 [ㅎ+ㅚ] + 사 [ㅅ+ㅏ] + 원 [ㅇ+ㅝ+ㄴ]", hanja: "會社員", ex: "제 친구는 회사원이에요. (Můj kamarád je úředník.)" },
  { hangul: "경찰", roman: "gyeongchal", cz: "policie / policista", cat: "people", emoji: "👮", decomp: "경 [ㄱ+ㅕ+ㅇ] + 찰 [ㅊ+ㅏ+ㄹ]", hanja: "警察", ex: "경찰관이 도와주었어요. (Policista mi pomohl.)" },
  { hangul: "아이 / 애", roman: "a-i / ae", cz: "dítě", cat: "people", emoji: "👶", decomp: "아 [ㅇ+ㅏ] + 이 [ㅇ+ㅣ]", hanja: "", ex: "아이가 웃고 있어요. (Dítě se směje.)" },
  { hangul: "남자", roman: "namja", cz: "muž", cat: "people", emoji: "👨", decomp: "남 [ㄴ+ㅏ+ㅁ] + 자 [ㅈ+ㅏ]", hanja: "男子", ex: "키가 큰 남자예요. (Je to vysoký muž.)" },
  { hangul: "여자", roman: "yeoja", cz: "žena", cat: "people", emoji: "👩", decomp: "여 [ㅇ+ㅕ] + 자 [ㅈ+ㅏ]", hanja: "女子", ex: "저 여자는 누구예요? (Kdo je tamta žena?)" },

  // ─── 2. JÍDLO, NÁPOJE & RESTAURACE (50 slov) ───
  { hangul: "밥", roman: "bap", cz: "vařená rýže / jídlo", cat: "food", emoji: "🍚", decomp: "밥 [ㅂ+ㅏ+ㅂ]", hanja: "", ex: "밥 먹었어요? (Jedl jsi? / Jak se máš?)" },
  { hangul: "물", roman: "mul", cz: "voda", cat: "food", emoji: "💧", decomp: "물 [ㅁ+ㅜ+ㄹ]", hanja: "", ex: "시원한 물 한 잔 주세요. (Dejte mi prosím sklenici studené vody.)" },
  { hangul: "김치", roman: "kimchi", cz: "kimči (fermentované zelí)", cat: "food", emoji: "🥬", decomp: "김 [ㄱ+ㅣ+ㅁ] + 치 [ㅊ+ㅣ]", hanja: "", ex: "김치가 매워요. (Kimči je pálivé.)" },
  { hangul: "불고기", roman: "bulgogi", cz: "bulgogi (marinované hovězí)", cat: "food", emoji: "🥩", decomp: "불 [ㅂ+ㅜ+ㄹ] + 고 [ㄱ+ㅗ] + 기 [ㄱ+ㅣ]", hanja: "", ex: "불고기가 정말 맛있어요. (Bulgogi je opravdu výborné.)" },
  { hangul: "비빔밥", roman: "bibimbap", cz: "bibimbap (míchaná rýže se zeleninou)", cat: "food", emoji: "🍲", decomp: "비 [ㅂ+ㅣ] + 빔 [ㅂ+ㅣ+ㅁ] + 밥 [ㅂ+ㅏ+ㅂ]", hanja: "", ex: "전주 비빔밥을 먹었어요. (Měl jsem bíbimbap z Čondžu.)" },
  { hangul: "찌개", roman: "jjigae", cz: "korejský kotlík / hustá polévka", cat: "food", emoji: "🥘", decomp: "찌 [ㅉ+ㅣ] + 개 [ㄱ+ㅐ]", hanja: "", ex: "김치찌개를 주문했어요. (Objednal jsem si kimčchi-ččige.)" },
  { hangul: "삼겹살", roman: "samgyeopsal", cz: "vepřový bůček na grilu", cat: "food", emoji: "🥓", decomp: "삼 [ㅅ+ㅏ+ㅁ] + 겹 [ㄱ+ㅕ+ㅂ] + 살 [ㅅ+ㅏ+ㄹ]", hanja: "三겹살", ex: "오늘 저녁은 삼겹살이에요! (K dnešní večeři je samgjopsal!)" },
  { hangul: "라면", roman: "ramyeon", cz: "korejské pikantní nudle", cat: "food", emoji: "🍜", decomp: "라 [ㄹ+ㅏ] + 면 [ㅁ+ㅕ+ㄴ]", hanja: "拉麵", ex: "라면 끓여 먹을까요? (Uvaříme si ramen?)" },
  { hangul: "치킨", roman: "chikin", cz: "smažené kuře (K-Chicken)", cat: "food", emoji: "🍗", decomp: "치 [ㅊ+ㅣ] + 킨 [ㅋ+ㅣ+ㄴ]", hanja: "", ex: "치맥(치킨과 맥주) 먹자! (Dáme si kuře a pivo!)" },
  { hangul: "떡볶이", roman: "tteokbokki", cz: "rýžové válečky v pálivé omáčce", cat: "food", emoji: "🍢", decomp: "떡 [ㄸ+ㅓ+ㄱ] + 볶 [ㅂ+ㅗ+ㄲ] + 이 [ㅇ+ㅣ]", hanja: "", ex: "시장 떡볶이가 최고예요. (Trhový tteokbokki je nejlepší.)" },
  { hangul: "고기", roman: "gogi", cz: "maso", cat: "food", emoji: "🍖", decomp: "고 [ㄱ+ㅗ] + 기 [ㄱ+ㅣ]", hanja: "", ex: "소고기와 돼지고기 (Hovězí a vepřové maso)" },
  { hangul: "생선", roman: "saengseon", cz: "ryba (k jídlu)", cat: "food", emoji: "🐟", decomp: "생 [ㅅ+ㅐ+ㅇ] + 선 [ㅅ+ㅓ+ㄴ]", hanja: "生鮮", ex: "생선 구이를 먹어요. (Jím pečenou rybu.)" },
  { hangul: "계란 / 달걀", roman: "gyeran / dalgyal", cz: "vejce", cat: "food", emoji: "🥚", decomp: "계 [ㄱ+ㅖ] + 란 [ㄹ+ㅏ+ㄴ]", hanja: "鷄卵", ex: "계란 후라이 두 개 (Dvě volská oka)" },
  { hangul: "빵", roman: "ppang", cz: "chléb / pečivo", cat: "food", emoji: "🍞", decomp: "빵 [ㅃ+ㅏ+ㅇ]", hanja: "", ex: "베이커리에서 빵을 샀어요. (V pekárně jsem koupil chléb.)" },
  { hangul: "사과", roman: "sagwa", cz: "jablko", cat: "food", emoji: "🍎", decomp: "사 [ㅅ+ㅏ] + 과 [ㄱ+ㅘ]", hanja: "沙果", ex: "아침 사과는 보약이에요. (Ranní jablko je lék.)" },
  { hangul: "바나나", roman: "banana", cz: "banán", cat: "food", emoji: "🍌", decomp: "바 [ㅂ+ㅏ] + 나 [ㄴ+ㅏ] + 나 [ㄴ+ㅏ]", hanja: "", ex: "바나나 우유가 달콤해요. (Banánové mléko je sladké.)" },
  { hangul: "딸기", roman: "ttalgi", cz: "jahoda", cat: "food", emoji: "🍓", decomp: "딸 [ㄸ+ㅏ+ㄹ] + 기 [ㄱ+ㅣ]", hanja: "", ex: "한국 딸기는 아주 달아요. (Korejské jahody jsou velmi sladké.)" },
  { hangul: "수박", roman: "subak", cz: "vodní meloun", cat: "food", emoji: "🍉", decomp: "수 [ㅅ+ㅜ] + 박 [ㅂ+ㅏ+ㄱ]", hanja: "水박", ex: "여름엔 시원한 수박! (V létě osvěžující meloun!)" },
  { hangul: "포도", roman: "podo", cz: "hroznové víno", cat: "food", emoji: "🍇", decomp: "포 [ㅍ+ㅗ] + 도 [ㄷ+ㅗ]", hanja: "葡萄", ex: "포도 한 송이 (Jeden hrozen vína)" },
  { hangul: "커피", roman: "keopi", cz: "káva", cat: "food", emoji: "☕", decomp: "커 [ㅋ+ㅓ] + 피 [ㅍ+ㅣ]", hanja: "", ex: "아이스 아메리카노(아아) 한 잔 주세요. (Jedno ledové americano, prosím.)" },
  { hangul: "차", roman: "cha", cz: "čaj", cat: "food", emoji: "🍵", decomp: "차 [ㅊ+ㅏ]", hanja: "茶", ex: "따뜻한 녹차를 마셔요. (Piji teplý zelený čaj.)" },
  { hangul: "우유", roman: "uyu", cz: "mléko", cat: "food", emoji: "🥛", decomp: "우 [ㅇ+ㅜ] + 유 [ㅇ+ㅠ]", hanja: "牛乳", ex: "신선한 우유 (Čerstvé mléko)" },
  { hangul: "맥주", roman: "maekju", cz: "pivo", cat: "food", emoji: "🍺", decomp: "맥 [ㅁ+ㅐ+ㄱ] + 주 [ㅈ+ㅜ]", hanja: "麥酒", ex: "시원한 맥주 한잔합시다! (Dejme si sklenici studeného piva!)" },
  { hangul: "소주", roman: "soju", cz: "sodžu (tradiční pálenka)", cat: "food", emoji: "🍶", decomp: "소 [ㅅ+ㅗ] + 주 [ㅈ+ㅜ]", hanja: "燒酒", ex: "소주 한 병 주세요. (Jednu láhev sodžu, prosím.)" },
  { hangul: "식당", roman: "sikdang", cz: "restaurace / jídelna", cat: "food", emoji: "🍽️", decomp: "식 [ㅅ+ㅣ+ㄱ] + 당 [ㄷ+ㅏ+ㅇ]", hanja: "食堂", ex: "근처에 맛있는 식당이 있어요. (Poblíž je chutná restaurace.)" },

  // ─── 3. DOMOV & KAŽDODENNÍ PŘEDMĚTY (45 slov) ───
  { hangul: "집", roman: "jip", cz: "dům / domov", cat: "home", emoji: "🏠", decomp: "집 [ㅈ+ㅣ+ㅂ]", hanja: "", ex: "집에 가고 싶어요. (Chci jít domů.)" },
  { hangul: "방", roman: "bang", cz: "pokoj / místnost", cat: "home", emoji: "🚪", decomp: "방 [ㅂ+ㅏ+ㅇ]", hanja: "房", ex: "내 방을 청소했어요. (Uklidil jsem svůj pokoj.)" },
  { hangul: "문", roman: "mun", cz: "dveře", cat: "home", emoji: "🚪", decomp: "문 [ㅁ+ㅜ+ㄴ]", hanja: "門", ex: "문을 닫아 주세요. (Zavřete prosím dveře.)" },
  { hangul: "창문", roman: "changmun", cz: "okno", cat: "home", emoji: "🪟", decomp: "창 [ㅊ+ㅏ+ㅇ] + 문 [ㅁ+ㅜ+ㄴ]", hanja: "窓門", ex: "창문을 열어요. (Otvírám okno.)" },
  { hangul: "책상", roman: "chaeksang", cz: "psací stůl", cat: "home", emoji: "🛋️", decomp: "책 [ㅊ+ㅐ+ㄱ] + 상 [ㅅ+ㅏ+ㅇ]", hanja: "冊床", ex: "책상 위에 컴퓨터가 있어요. (Na stole je počítač.)" },
  { hangul: "의자", roman: "uija", cz: "židle", cat: "home", emoji: "🪑", decomp: "의 [ㅇ+ㅢ] + 자 [ㅈ+ㅏ]", hanja: "椅子", ex: "의자에 앉으세요. (Posaďte se na židli.)" },
  { hangul: "침대", roman: "chimdae", cz: "postel", cat: "home", emoji: "🛏️", decomp: "침 [ㅊ+ㅣ+ㅁ] + 대 [ㄷ+ㅐ]", hanja: "寢臺", ex: "침대에 누웠어요. (Lehl jsem si na postel.)" },
  { hangul: "책", roman: "chaek", cz: "kniha", cat: "home", emoji: "📚", decomp: "책 [ㅊ+ㅐ+ㄱ]", hanja: "冊", ex: "책을 읽고 있어요. (Čtu knihu.)" },
  { hangul: "공책", roman: "gongchaek", cz: "sešit / poznámkový blok", cat: "home", emoji: "📓", decomp: "공 [ㄱ+ㅗ+ㅇ] + 책 [ㅊ+ㅐ+ㄱ]", hanja: "空冊", ex: "공책에 메모해요. (Dělám si poznámky do sešitu.)" },
  { hangul: "연필", roman: "yeonpil", cz: "tužka", cat: "home", emoji: "✏️", decomp: "연 [ㅇ+ㅕ+ㄴ] + 필 [ㅍ+ㅣ+ㄹ]", hanja: "鉛筆", ex: "연필로 글을 써요. (Píšu tužkou.)" },
  { hangul: "볼펜", roman: "bolpen", cz: "kuličkové pero", cat: "home", emoji: "🖊️", decomp: "볼 [ㅂ+ㅗ+ㄹ] + 펜 [ㅍ+ㅔ+ㄴ]", hanja: "", ex: "검은색 볼펜 (Černá propiska)" },
  { hangul: "가방", roman: "gabang", cz: "taška / batoh", cat: "home", emoji: "🎒", decomp: "가 [ㄱ+ㅏ] + 방 [ㅂ+ㅏ+ㅇ]", hanja: "", ex: "가방이 무거워요. (Taška je těžká.)" },
  { hangul: "컴퓨터", roman: "keompyuteo", cz: "počítač", cat: "home", emoji: "💻", decomp: "컴 [ㅋ+ㅓ+ㅁ] + 퓨 [ㅍ+ㅠ] + 터 [ㅌ+ㅓ]", hanja: "", ex: "컴퓨터로 코딩해요. (Kóduji na počítači.)" },
  { hangul: "스마트폰 / 핸드폰", roman: "seumateupon", cz: "smartphone / mobil", cat: "home", emoji: "📱", decomp: "핸 [ㅎ+ㅐ+ㄴ] + 드 [ㄷ+ㅡ] + 폰 [ㅍ+ㅗ+ㄴ]", hanja: "", ex: "핸드폰을 어디에 두었지? (Kam jsem dal telefon?)" },
  { hangul: "시계", roman: "sigye", cz: "hodiny / hodinky", cat: "home", emoji: "⌚", decomp: "시 [ㅅ+ㅣ] + 계 [ㄱ+ㅖ]", hanja: "時計", ex: "지금 시계를 보세요. (Podívej se teď na hodinky.)" },
  { hangul: "옷", roman: "ot", cz: "oblečení / šaty", cat: "home", emoji: "👗", decomp: "옷 [ㅇ+ㅗ+ㅅ]", hanja: "", ex: "따뜻한 옷을 입으세요. (Oblečte si teplé oblečení.)" },
  { hangul: "신발", roman: "sinbal", cz: "boty", cat: "home", emoji: "👟", decomp: "신 [ㅅ+ㅣ+ㄴ] + 발 [ㅂ+ㅏ+ㄹ]", hanja: "", ex: "현관에서 신발을 벗어요. (V předsíni si zujeme boty.)" },
  { hangul: "안경", roman: "angyeong", cz: "brýle", cat: "home", emoji: "👓", decomp: "안 [ㅇ+ㅏ+ㄴ] + 경 [ㄱ+ㅕ+ㅇ]", hanja: "眼鏡", ex: "안경을 써야 잘 보여요. (Musím si vzít brýle, abych viděl.)" },
  { hangul: "우산", roman: "usan", cz: "deštník", cat: "home", emoji: "☂️", decomp: "우 [ㅇ+ㅜ] + 산 [ㅅ+ㅏ+ㄴ]", hanja: "雨傘", ex: "비가 오니까 우산 챙겨! (Prší, vezmi si deštník!)" },
  { hangul: "지갑", roman: "jigap", cz: "peněženka", cat: "home", emoji: "👛", decomp: "지 [ㅈ+ㅣ] + 갑 [ㄱ+ㅏ+ㅂ]", hanja: "紙匣", ex: "지갑에 돈이 없어요. (V peněžence nemám peníze.)" },

  // ─── 4. MĚSTO, DOPRAVA & ORIENTACE (40 slov) ───
  { hangul: "서울", roman: "Seoul", cz: "Soul (hlavní město)", cat: "city", emoji: "🏙️", decomp: "서 [ㅅ+ㅓ] + 울 [ㅇ+ㅜ+ㄹ]", hanja: "", ex: "서울은 밤에도 밝아요. (Soul svítí i v noci.)" },
  { hangul: "한국", roman: "Hanguk", cz: "Korea (Korejská republika)", cat: "city", emoji: "🇰🇷", decomp: "한 [ㅎ+ㅏ+ㄴ] + 국 [ㄱ+ㅜ+ㄱ]", hanja: "韓國", ex: "한국에 여행 가고 싶어요. (Chci cestovat do Koreje.)" },
  { hangul: "길", roman: "gil", cz: "cesta / ulice", cat: "city", emoji: "🛣️", decomp: "길 [ㄱ+ㅣ+ㄹ]", hanja: "", ex: "길을 잃어버렸어요. (Ztratil jsem se.)" },
  { hangul: "지하철", roman: "jihacheol", cz: "metro", cat: "city", emoji: "🚇", decomp: "지 [ㅈ+ㅣ] + 하 [ㅎ+ㅏ] + 철 [ㅊ+ㅓ+ㄹ]", hanja: "地下鐵", ex: "지하철 2호선을 타세요. (Nasedněte na metro linku 2.)" },
  { hangul: "버스", roman: "beoseu", cz: "autobus", cat: "city", emoji: "🚌", decomp: "버 [ㅂ+ㅓ] + 스 [ㅅ+ㅡ]", hanja: "", ex: "버스가 곧 도착해요. (Autobus brzy dorazí.)" },
  { hangul: "택시", roman: "taeksi", cz: "taxi", cat: "city", emoji: "🚕", decomp: "택 [ㅌ+ㅐ+ㄱ] + 시 [ㅅ+ㅣ]", hanja: "", ex: "택시를 타고 가요. (Pojedeme taxíkem.)" },
  { hangul: "기차", roman: "gicha", cz: "vlak", cat: "city", emoji: "🚆", decomp: "기 [ㄱ+ㅣ] + 차 [ㅊ+ㅏ]", hanja: "汽車", ex: "KTX 고속기차 (Vysokorychlostní vlak KTX)" },
  { hangul: "비행기", roman: "bihaenggi", cz: "letadlo", cat: "city", emoji: "✈️", decomp: "비 [ㅂ+ㅣ] + 행 [ㅎ+ㅐ+ㅇ] + 기 [ㄱ+ㅣ]", hanja: "飛行機", ex: "인천공항에서 비행기를 타요. (V Incheonu nasedám na letadlo.)" },
  { hangul: "역", roman: "yeok", cz: "stanice / nádraží", cat: "city", emoji: "🚉", decomp: "역 [ㅇ+ㅕ+ㄱ]", hanja: "驛", ex: "서울역에서 만나요. (Potkáme se na nádraží v Soulu.)" },
  { hangul: "공항", roman: "gonghang", cz: "letiště", cat: "city", emoji: "🛫", decomp: "공 [ㄱ+ㅗ+ㅇ] + 항 [ㅎ+ㅏ+ㅇ]", hanja: "空港", ex: "공항철도를 타요. (Pojedu letištním expresem.)" },
  { hangul: "병원", roman: "byeong-won", cz: "nemocnice", cat: "city", emoji: "🏥", decomp: "병 [ㅂ+ㅕ+ㅇ] + 원 [ㅇ+ㅝ+ㄴ]", hanja: "病院", ex: "아프면 병원에 가세요. (Pokud jste nemocní, jděte do nemocnice.)" },
  { hangul: "약국", roman: "yakguk", cz: "lékárna", cat: "city", emoji: "💊", decomp: "약 [ㅇ+ㅑ+ㄱ] + 국 [ㄱ+ㅜ+ㄱ]", hanja: "藥局", ex: "약국에서 감기약을 샀어요. (V lékárně jsem koupil lék na nachlazení.)" },
  { hangul: "은행", roman: "eunhaeng", cz: "banka", cat: "city", emoji: "🏦", decomp: "은 [ㅇ+ㅡ+ㄴ] + 행 [ㅎ+ㅐ+ㅇ]", hanja: "銀行", ex: "은행에서 환전해요. (Směním peníze v bance.)" },
  { hangul: "마트 / 시장", roman: "mateu / sijang", cz: "supermarket / trh", cat: "city", emoji: "🛒", decomp: "시 [ㅅ+ㅣ] + 장 [ㅈ+ㅏ+ㅇ]", hanja: "市場", ex: "전통시장에서 장을 봐요. (Nakupuji na tradičním trhu.)" },
  { hangul: "카페", roman: "kape", cz: "kavárna", cat: "city", emoji: "☕", decomp: "카 [ㅋ+ㅏ] + 페 [ㅍ+ㅔ]", hanja: "", ex: "카페에서 공부해요. (Učím se v kavárně.)" },
  { hangul: "학교", roman: "hakgyo", cz: "škola", cat: "city", emoji: "🏫", decomp: "학 [ㅎ+ㅏ+ㄱ] + 교 [ㄱ+ㅛ]", hanja: "學校", ex: "학교에 일찍 왔어요. (Přišel jsem do školy brzy.)" },
  { hangul: "대학교", roman: "daehakgyo", cz: "univerzita", cat: "city", emoji: "🏛️", decomp: "대 [ㄷ+ㅐ] + 학 [ㅎ+ㅏ+ㄱ] + 교 [ㄱ+ㅛ]", hanja: "大學校", ex: "대학교 캠퍼스 (Univerzitní kampus)" },
  { hangul: "호텔", roman: "hotel", cz: "hotel", cat: "city", emoji: "🏨", decomp: "호 [ㅎ+ㅗ] + 텔 [ㅌ+ㅔ+ㄹ]", hanja: "", ex: "호텔을 예약했어요. (Zarezervoval jsem si hotel.)" },
  { hangul: "화장실", roman: "hwajangsil", cz: "toaleta / WC", cat: "city", emoji: "🚻", decomp: "화 [ㅎ+ㅘ] + 장 [ㅈ+ㅏ+ㅇ] + 실 [ㅅ+ㅣ+ㄹ]", hanja: "化粧室", ex: "화장실이 어디예요? (Kde je toaleta?)" },

  // ─── 5. PŘÍRODA, ZVÍŘATA & POČASÍ (40 slov) ───
  { hangul: "하늘", roman: "haneul", cz: "nebe / obloha", cat: "nature", emoji: "☁️", decomp: "하 [ㅎ+ㅏ] + 늘 [ㄴ+ㅡ+ㄹ]", hanja: "", ex: "하늘이 파랗고 맑아요. (Nebe je modré a jasné.)" },
  { hangul: "해 / 태양", roman: "hae / taeyang", cz: "slunce", cat: "nature", emoji: "☀️", decomp: "태 [ㅌ+ㅐ] + 양 [ㅇ+ㅑ+ㅇ]", hanja: "太陽", ex: "해가 떴어요. (Slunce vyšlo.)" },
  { hangul: "달", roman: "dal", cz: "měsíc (na nebi)", cat: "nature", emoji: "🌙", decomp: "달 [ㄷ+ㅏ+ㄹ]", hanja: "", ex: "보름달이 밝아요. (Úplněk jasně září.)" },
  { hangul: "별", roman: "byeol", cz: "hvězda", cat: "nature", emoji: "⭐", decomp: "별 [ㅂ+ㅕ+ㄹ]", hanja: "", ex: "밤하늘에 별이 많아요. (Na noční obloze je mnoho hvězd.)" },
  { hangul: "산", roman: "san", cz: "hora / pohoří", cat: "nature", emoji: "⛰️", decomp: "산 [ㅅ+ㅏ+ㄴ]", hanja: "山", ex: "설악산에 등산 가요. (Jdu na túru na horu Seoraksan.)" },
  { hangul: "바다", roman: "bada", cz: "moře", cat: "nature", emoji: "🌊", decomp: "바 [ㅂ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "부산 바다가 아름다워요. (Moře v Pusanu je nádherné.)" },
  { hangul: "강", roman: "gang", cz: "řeka", cat: "nature", emoji: "🏞️", decomp: "강 [ㄱ+ㅏ+ㅇ]", hanja: "江", ex: "한강 공원에서 자전거를 타요. (Jezdím na kole v parku podél řeky Han.)" },
  { hangul: "비", roman: "bi", cz: "déšť", cat: "nature", emoji: "🌧️", decomp: "비 [ㅂ+ㅣ]", hanja: "", ex: "비가 내리고 있어요. (Prší.)" },
  { hangul: "눈", roman: "nun", cz: "sníh (i oko)", cat: "nature", emoji: "❄️", decomp: "눈 [ㄴ+ㅜ+ㄴ]", hanja: "", ex: "하얀 눈이 내려요. (Padá bílý sníh.)" },
  { hangul: "바람", roman: "baram", cz: "vítr", cat: "nature", emoji: "💨", decomp: "바 [ㅂ+ㅏ] + 람 [ㄹ+ㅏ+ㅁ]", hanja: "", ex: "시원한 바람이 불어요. (Fouká příjemný vánek.)" },
  { hangul: "구름", roman: "gureum", cz: "mrak / oblak", cat: "nature", emoji: "⛅", decomp: "구 [ㄱ+ㅜ] + 름 [ㄹ+ㅡ+ㅁ]", hanja: "", ex: "구름이 걷히고 있어요. (Mraky se protrhávají.)" },
  { hangul: "꽃", roman: "kkot", cz: "květina", cat: "nature", emoji: "🌸", decomp: "꽃 [ㄲ+ㅗ+ㅊ]", hanja: "", ex: "봄에 벚꽃이 피어요. (Na jaře kvetou třešňové květy.)" },
  { hangul: "나무", roman: "namu", cz: "strom / dřevo", cat: "nature", emoji: "🌳", decomp: "나 [ㄴ+ㅏ] + 무 [ㅁ+ㅜ]", hanja: "", ex: "큰 나무 그늘 (Stín velkého stromu)" },
  { hangul: "강아지 / 개", roman: "gang-aji / gae", cz: "štěně / pes", cat: "nature", emoji: "🐶", decomp: "강 [ㄱ+ㅏ+ㅇ] + 아 [ㅇ+ㅏ] + 지 [ㅈ+ㅣ]", hanja: "", ex: "강아지가 꼬리를 흔들어요. (Štěně vrtí ocáskem.)" },
  { hangul: "고양이", roman: "goyangi", cz: "kočka", cat: "nature", emoji: "🐱", decomp: "고 [ㄱ+ㅗ] + 양 [ㅇ+ㅑ+ㅇ] + 이 [ㅇ+ㅣ]", hanja: "", ex: "귀여운 길고양이 (Roztomilá pouliční kočička)" },
  { hangul: "새", roman: "sae", cz: "pták", cat: "nature", emoji: "🐦", decomp: "새 [ㅅ+ㅐ]", hanja: "", ex: "새가 노래해요. (Ptáček zpívá.)" },
  { hangul: "물고기", roman: "mulgogi", cz: "ryba (živá)", cat: "nature", emoji: "🐠", decomp: "물 [ㅁ+ㅜ+ㄹ] + 고 [ㄱ+ㅗ] + 기 [ㄱ+ㅣ]", hanja: "", ex: "어항 속 물고기 (Ryba v akváriu)" },
  { hangul: "날씨", roman: "nalssi", cz: "počasí", cat: "nature", emoji: "☀️", decomp: "날 [ㄴ+ㅏ+ㄹ] + 씨 [ㅆ+ㅣ]", hanja: "", ex: "오늘 날씨가 참 좋아요. (Dnes je opravdu hezké počasí.)" },

  // ─── 6. ČAS, DNY & ROČNÍ OBDOBÍ (35 slov) ───
  { hangul: "오늘", roman: "oneul", cz: "dnes", cat: "time", emoji: "📅", decomp: "오 [ㅇ+ㅗ] + 늘 [ㄴ+ㅡ+ㄹ]", hanja: "", ex: "오늘 뭐 해요? (Co dnes děláš?)" },
  { hangul: "어제", roman: "eoje", cz: "včera", cat: "time", emoji: "⏮️", decomp: "어 [ㅇ+ㅓ] + 제 [ㅈ+ㅔ]", hanja: "", ex: "어제 영화를 봤어요. (Včera jsem se díval na film.)" },
  { hangul: "내일", roman: "naeil", cz: "zítra", cat: "time", emoji: "⏭️", decomp: "내 [ㄴ+ㅐ] + 일 [ㅇ+ㅣ+ㄹ]", hanja: "來日", ex: "내일 만나요! (Uvidíme se zítra!)" },
  { hangul: "지금", roman: "jigeum", cz: "teď / právě teď", cat: "time", emoji: "⏱️", decomp: "지 [ㅈ+ㅣ] + 금 [ㄱ+ㅡ+ㅁ]", hanja: "只今", ex: "지금 몇 시예요? (Kolik je teď hodin?)" },
  { hangul: "아침", roman: "achim", cz: "ráno / snídaně", cat: "time", emoji: "🌅", decomp: "아 [ㅇ+ㅏ] + 침 [ㅊ+ㅣ+ㅁ]", hanja: "", ex: "좋은 아침이에요! (Dobré ráno!)" },
  { hangul: "점심", roman: "jeomsim", cz: "poledne / oběd", cat: "time", emoji: "🥪", decomp: "점 [ㅈ+ㅓ+ㅁ] + 심 [ㅅ+ㅣ+ㅁ]", hanja: "點心", ex: "점심 맛있게 드세요. (Dobrou chuť k obědu.)" },
  { hangul: "저녁", roman: "jeonyeok", cz: "večer / večeře", cat: "time", emoji: "🌆", decomp: "저 [ㅈ+ㅓ] + 녁 [ㄴ+ㅕ+ㄱ]", hanja: "", ex: "저녁 7시에 만나요. (Potkáme se v 7 večer.)" },
  { hangul: "밤", roman: "bam", cz: "noc", cat: "time", emoji: "🌃", decomp: "밤 [ㅂ+ㅏ+ㅁ]", hanja: "", ex: "안녕히 주무세요, 좋은 밤! (Dobrou noc!)" },
  { hangul: "월요일", roman: "woryoil", cz: "pondělí", cat: "time", emoji: "🌙", decomp: "월 [ㅇ+ㅝ+ㄹ] + 요 [ㅇ+ㅛ] + 일 [ㅇ+ㅣ+ㄹ]", hanja: "月曜日", ex: "월요일 아침 (Pondělní ráno)" },
  { hangul: "금요일", roman: "geumyoil", cz: "pátek (불금 = ohnivý pátek TGIF)", cat: "time", emoji: "🔥", decomp: "금 [ㄱ+ㅡ+ㅁ] + 요 [ㅇ+ㅛ] + 일 [ㅇ+ㅣ+ㄹ]", hanja: "金曜日", ex: "불타는 금요일! (Zapálený pátek / TGIF!)" },
  { hangul: "주말", roman: "jumal", cz: "víkend", cat: "time", emoji: "🎉", decomp: "주 [ㅈ+ㅜ] + 말 [ㅁ+ㅏ+ㄹ]", hanja: "週末", ex: "주말 잘 보내세요! (Přeji hezký víkend!)" },
  { hangul: "봄", roman: "bom", cz: "jaro", cat: "time", emoji: "🌱", decomp: "봄 [ㅂ+ㅗ+ㅁ]", hanja: "", ex: "따뜻한 봄이 왔어요. (Přišlo teplé jaro.)" },
  { hangul: "여름", roman: "yeoreum", cz: "léto", cat: "time", emoji: "☀️", decomp: "여 [ㅇ+ㅕ] + 름 [ㄹ+ㅡ+ㅁ]", hanja: "", ex: "여름 방학 (Letní prázdniny)" },
  { hangul: "가을", roman: "ga-eul", cz: "podzim", cat: "time", emoji: "🍁", decomp: "가 [ㄱ+ㅏ] + 을 [ㅇ+ㅡ+ㄹ]", hanja: "", ex: "가을 단풍이 예뻐요. (Podzimní barevné listí je krásné.)" },
  { hangul: "겨울", roman: "gyeoul", cz: "zima", cat: "time", emoji: "⛄", decomp: "겨 [ㄱ+ㅕ] + 울 [ㅇ+ㅜ+ㄹ]", hanja: "", ex: "겨울에는 눈이 와요. (V zimě padá sníh.)" },

  // ─── 7. KLÍČOVÁ SLOVESA (50 slov) ───
  { hangul: "가다", roman: "gada", cz: "jít / jet", cat: "verbs", emoji: "🚶", decomp: "가 [ㄱ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "학교에 가요. (Jdu do školy.)" },
  { hangul: "오다", roman: "oda", cz: "přijít / přijet", cat: "verbs", emoji: "🏃", decomp: "오 [ㅇ+ㅗ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "친구가 집에 와요. (Kamarád jde ke mně domů.)" },
  { hangul: "먹다", roman: "meokda", cz: "jíst", cat: "verbs", emoji: "🍽️", decomp: "먹 [ㅁ+ㅓ+ㄱ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "사과를 먹어요. (Jím jablko.)" },
  { hangul: "마시다", roman: "masida", cz: "pít", cat: "verbs", emoji: "🥤", decomp: "마 [ㅁ+ㅏ] + 시 [ㅅ+ㅣ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "물을 마셔요. (Piji vodu.)" },
  { hangul: "보다", roman: "boda", cz: "vidět / dívat se", cat: "verbs", emoji: "👀", decomp: "보 [ㅂ+ㅗ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "K-드라마를 봐요. (Dívám se na K-drama.)" },
  { hangul: "듣다", roman: "deutda", cz: "slyšet / poslouchat", cat: "verbs", emoji: "🎧", decomp: "듣 [ㄷ+ㅡ+ㄷ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "음악을 들어요. (Poslouchám hudbu.)" },
  { hangul: "읽다", roman: "ikda", cz: "číst", cat: "verbs", emoji: "📖", decomp: "읽 [ㅇ+ㅣ+ㄹ+ㄱ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "책을 읽어요. (Čtu knihu.)" },
  { hangul: "쓰다", roman: "sseuda", cz: "psát / používat / hořký", cat: "verbs", emoji: "✍️", decomp: "쓰 [ㅆ+ㅡ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "한글을 써요. (Píšu Hangul.)" },
  { hangul: "말하다", roman: "malhada", cz: "mluvit / říkat", cat: "verbs", emoji: "🗣️", decomp: "말 [ㅁ+ㅏ+ㄹ] + 하 [ㅎ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "한국어로 말해요. (Mluvím korejsky.)" },
  { hangul: "자다", roman: "jada", cz: "spát", cat: "verbs", emoji: "😴", decomp: "자 [ㅈ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "일찍 자요. (Jdu spát brzy.)" },
  { hangul: "일어나다", roman: "ireonada", cz: "vstávat / probudit se", cat: "verbs", emoji: "⏰", decomp: "일 [ㅇ+ㅣ+ㄹ] + 어 [ㅇ+ㅓ] + 나 [ㄴ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "아침 7시에 일어나요. (Vstávám v 7 ráno.)" },
  { hangul: "일하다", roman: "ilhada", cz: "pracovat", cat: "verbs", emoji: "💼", decomp: "일 [ㅇ+ㅣ+ㄹ] + 하 [ㅎ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "열심히 일해요. (Pracuji pilně.)" },
  { hangul: "공부하다", roman: "gongbuhada", cz: "učit se / studovat", cat: "verbs", emoji: "📝", decomp: "공 [ㄱ+ㅗ+ㅇ] + 부 [ㅂ+ㅜ] + 하 [ㅎ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "工夫하다", ex: "매일 한국어를 공부해요. (Každý den studuji korejštinu.)" },
  { hangul: "사다", roman: "sada", cz: "koupit", cat: "verbs", emoji: "🛍️", decomp: "사 [ㅅ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "선물을 샀어요. (Koupil jsem dárek.)" },
  { hangul: "만나다", roman: "mannada", cz: "potkat / setkat se", cat: "verbs", emoji: "👋", decomp: "만 [ㅁ+ㅏ+ㄴ] + 나 [ㄴ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "내일 친구를 만나요. (Zítra se potkám s kamarádem.)" },
  { hangul: "기다리다", roman: "gidarida", cz: "čekat", cat: "verbs", emoji: "⏳", decomp: "기 [ㄱ+ㅣ] + 다 [ㄷ+ㅏ] + 리 [ㄹ+ㅣ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "조금만 기다려 주세요. (Počkejte prosím chviličku.)" },
  { hangul: "알다", roman: "alda", cz: "vědět / znát", cat: "verbs", emoji: "💡", decomp: "알 [ㅇ+ㅏ+ㄹ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "네, 알겠습니다! (Ano, rozumím!)" },
  { hangul: "모르다", roman: "moreuda", cz: "nevědět / neznat", cat: "verbs", emoji: "🤷", decomp: "모 [ㅁ+ㅗ] + 르 [ㄹ+ㅡ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "잘 모르겠어요. (Moc dobře tomu nerozumím.)" },
  { hangul: "만들다", roman: "mandeulda", cz: "vyrábět / tvořit", cat: "verbs", emoji: "🛠️", decomp: "만 [ㅁ+ㅏ+ㄴ] + 들 [ㄷ+ㅡ+ㄹ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "웹사이트를 만들어요. (Tvořím webovou stránku.)" },
  { hangul: "사랑하다", roman: "saranghada", cz: "milovat", cat: "verbs", emoji: "❤️", decomp: "사 [ㅅ+ㅏ] + 랑 [ㄹ+ㅏ+ㅇ] + 하 [ㅎ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "사랑해요! (Miluji tě!)" },

  // ─── 8. KLÍČOVÁ PŘÍDAVNÁ JMÉNA (45 slov) ───
  { hangul: "좋다", roman: "jota", cz: "být dobrý / líbit se", cat: "adjectives", emoji: "👍", decomp: "좋 [ㅈ+ㅗ+ㅎ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "기분이 정말 좋아요. (Mám opravdu dobrou náladu.)" },
  { hangul: "나쁘다", roman: "nappeuda", cz: "být špatný / zlý", cat: "adjectives", emoji: "👎", decomp: "나 [ㄴ+ㅏ] + 쁘 [ㅃ+ㅡ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "날씨가 나빠요. (Počasí je špatné.)" },
  { hangul: "크다", roman: "keuda", cz: "být velký / vysoký", cat: "adjectives", emoji: "🐘", decomp: "크 [ㅋ+ㅡ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "방이 아주 커요. (Pokoj je velmi velký.)" },
  { hangul: "작다", roman: "jakda", cz: "být malý", cat: "adjectives", emoji: "🐭", decomp: "작 [ㅈ+ㅏ+ㄱ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "글씨가 너무 작아요. (Písmenka jsou moc malá.)" },
  { hangul: "많다", roman: "manta", cz: "být mnoho / hodně", cat: "adjectives", emoji: "📈", decomp: "많 [ㅁ+ㅏ+ㄴ+ㅎ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "사람이 많아요. (Je tu hodně lidí.)" },
  { hangul: "적다", roman: "jeokda", cz: "být málo", cat: "adjectives", emoji: "📉", decomp: "적 [ㅈ+ㅓ+ㄱ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "시간이 적어요. (Je málo času.)" },
  { hangul: "빠르다", roman: "ppareuda", cz: "být rychlý", cat: "adjectives", emoji: "⚡", decomp: "빠 [ㅃ+ㅏ] + 르 [ㄹ+ㅡ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "기차가 빨라요. (Vlak je rychlý.)" },
  { hangul: "느리다", roman: "neurida", cz: "být pomalý", cat: "adjectives", emoji: "🐢", decomp: "느 [ㄴ+ㅡ] + 리 [ㄹ+ㅣ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "인터넷이 느려요. (Internet je pomalý.)" },
  { hangul: "예쁘다", roman: "yeppeuda", cz: "být hezký / půvabný", cat: "adjectives", emoji: "✨", decomp: "예 [ㅇ+ㅖ] + 쁘 [ㅃ+ㅡ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "꽃이 참 예뻐요. (Květina je opravdu krásná.)" },
  { hangul: "멋있다", roman: "meositda", cz: "být fešný / cool / úžasný", cat: "adjectives", emoji: "😎", decomp: "멋 [ㅁ+ㅓ+ㅅ] + 있 [ㅇ+ㅣ+ㅆ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "정말 멋있어요! (To je vážně skvělé/cool!)" },
  { hangul: "맛있다", roman: "masitda", cz: "být chutný / lahodný", cat: "adjectives", emoji: "😋", decomp: "맛 [ㅁ+ㅏ+ㅅ] + 있 [ㅇ+ㅣ+ㅆ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "한국 음식이 맛있어요. (Korejské jídlo je moc dobré.)" },
  { hangul: "맛없다", roman: "maseopda", cz: "být nechutný", cat: "adjectives", emoji: "🤢", decomp: "맛 [ㅁ+ㅏ+ㅅ] + 없 [ㅇ+ㅓ+ㅂ+ㅅ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "이건 맛없어요. (Tohle není dobré.)" },
  { hangul: "춥다", roman: "chupda", cz: "být chladno / studený", cat: "adjectives", emoji: "🥶", decomp: "춥 [ㅊ+ㅜ+ㅂ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "오늘 날씨가 추워요. (Dnes je zima.)" },
  { hangul: "덥다", roman: "deopda", cz: "být horko / teplý", cat: "adjectives", emoji: "🥵", decomp: "덥 [ㄷ+ㅓ+ㅂ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "여름엔 아주 더워요. (V létě je velké horko.)" },
  { hangul: "비싸다", roman: "bissada", cz: "být drahý", cat: "adjectives", emoji: "💎", decomp: "비 [ㅂ+ㅣ] + 싸 [ㅆ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "너무 비싸요, 깎아 주세요! (To je moc drahé, dejte mi slevu!)" },
  { hangul: "싸다", roman: "ssada", cz: "být levný", cat: "adjectives", emoji: "🏷️", decomp: "싸 [ㅆ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "가격이 싸고 좋아요. (Cena je nízká a fajn.)" },
  { hangul: "어렵다", roman: "eoryeopda", cz: "být těžký / obtížný", cat: "adjectives", emoji: "🤯", decomp: "어 [ㅇ+ㅓ] + 렵 [ㄹ+ㅕ+ㅂ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "문법이 조금 어려워요. (Gramatika je trochu těžká.)" },
  { hangul: "쉽다", roman: "swipda", cz: "být snadný / lehký", cat: "adjectives", emoji: "👌", decomp: "쉽 [ㅅ+ㅟ+ㅂ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "한글 읽기는 쉬워요! (Čtení Hangulu je snadné!)" },
  { hangul: "재미있다", roman: "jaemi-itda", cz: "být zajímavý / zábavný", cat: "adjectives", emoji: "🎮", decomp: "재 [ㅈ+ㅐ] + 미 [ㅁ+ㅣ] + 있 [ㅇ+ㅣ+ㅆ] + 다 [ㄷ+ㅏ]", hanja: "", ex: "한국어 공부가 재미있어요. (Učení korejštiny je zábavné.)" },
  { hangul: "행복하다", roman: "haengbokhada", cz: "být šťastný", cat: "adjectives", emoji: "🥰", decomp: "행 [ㅎ+ㅐ+ㅇ] + 복 [ㅂ+ㅗ+ㄱ] + 하 [ㅎ+ㅏ] + 다 [ㄷ+ㅏ]", hanja: "幸福하다", ex: "우리는 행복해요. (Jsme šťastní.)" }
];
