// ═══════════════════════════════════════════════════════
// ONLINE & CURATED CHINESE SENTENCE COLLECTIONS
// Authentic news, culture, chengyu, and course sentences
// ═══════════════════════════════════════════════════════

window.SENTENCE_COLLECTIONS = {
  // 📚 Course sentences (progression through learned characters)
  course: [
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"好",p:"hǎo",c:"dobrý",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Ahoj!" },
      { tiles:[{h:"大",p:"dà",c:"velký",cls:"l1"},{h:"家",p:"jiā",c:"rodina",cls:"l1"},{h:"好",p:"hǎo",c:"dobrý",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Ahoj všichni!" },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"好",p:"hǎo",c:"dobrý",cls:"adj"},{h:"吗",p:"ma",c:"(ot.)",cls:"particle"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Jak se máš?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"好",p:"hǎo",c:"dobrý",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Jsem velmi dobře!" },
      { tiles:[{h:"谢",p:"xiè",c:"díky",cls:"verb"},{h:"谢",p:"xiè",c:"díky",cls:"verb"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Děkuji!" },
      { tiles:[{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"客",p:"kè",c:"host",cls:"l1"},{h:"气",p:"qì",c:"vzduch",cls:"l1"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Není zač!" },
      { tiles:[{h:"再",p:"zài",c:"znovu",cls:"adv"},{h:"见",p:"jiàn",c:"vidět",cls:"verb"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Na shledanou!" },
      { tiles:[{h:"对",p:"duì",c:"správný",cls:"adj"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"起",p:"qǐ",c:"vstát",cls:"verb"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Promiňte!" },
      { tiles:[{h:"没",p:"méi",c:"ne-",cls:"adv"},{h:"关",p:"guān",c:"zavřít",cls:"verb"},{h:"系",p:"xì",c:"systém",cls:"l1"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Nevadí!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"是",p:"shì",c:"být",cls:"verb"},{h:"…",p:"",c:"",cls:"punct"}], czech:"Jsem …" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"叫",p:"jiào",c:"jmenuju se",cls:"verb"},{h:"…",p:"",c:"",cls:"punct"}], czech:"Jmenuji se …" },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"叫",p:"jiào",c:"jmenuješ se",cls:"verb"},{h:"什",p:"shén",c:"",cls:"l1"},{h:"么",p:"me",c:"co",cls:"particle"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Jak se jmenuješ?" },
      { tiles:[{h:"一",p:"yī",c:"1",cls:"num"},{h:"二",p:"èr",c:"2",cls:"num"},{h:"三",p:"sān",c:"3",cls:"num"}], czech:"Jedna, dvě, tři!" },
      { tiles:[{h:"四",p:"sì",c:"4",cls:"num"},{h:"五",p:"wǔ",c:"5",cls:"num"},{h:"六",p:"liù",c:"6",cls:"num"}], czech:"Čtyři, pět, šest!" },
      { tiles:[{h:"七",p:"qī",c:"7",cls:"num"},{h:"八",p:"bā",c:"8",cls:"num"},{h:"九",p:"jiǔ",c:"9",cls:"num"},{h:"十",p:"shí",c:"10",cls:"num"}], czech:"Sedm, osm, devět, deset!" },
      { tiles:[{h:"百",p:"bǎi",c:"100",cls:"num"},{h:"千",p:"qiān",c:"1000",cls:"num"},{h:"万",p:"wàn",c:"10 000",cls:"num"}], czech:"Sto, tisíc, deset tisíc!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"有",p:"yǒu",c:"mít",cls:"verb"},{h:"三",p:"sān",c:"tři",cls:"num"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"朋",p:"péng",c:"",cls:"l1"},{h:"友",p:"yǒu",c:"přítel",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Mám tři přátele." },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"有",p:"yǒu",c:"mít",cls:"verb"},{h:"几",p:"jǐ",c:"kolik",cls:"l1"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"朋",p:"péng",c:"",cls:"l1"},{h:"友",p:"yǒu",c:"přítel",cls:"l1"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Kolik máš přátel?" },
      { tiles:[{h:"他",p:"tā",c:"on",cls:"l1"},{h:"是",p:"shì",c:"být",cls:"verb"},{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"的",p:"de",c:"(přív.)",cls:"particle"},{h:"朋",p:"péng",c:"",cls:"l1"},{h:"友",p:"yǒu",c:"přítel",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"On je můj přítel." },
      { tiles:[{h:"她",p:"tā",c:"ona",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"漂",p:"piào",c:"",cls:"adj"},{h:"亮",p:"liàng",c:"krásná",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"Ona je velmi krásná." },
      { tiles:[{h:"他",p:"tā",c:"on",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"高",p:"gāo",c:"vysoký",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"On je velmi vysoký." },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"忙",p:"máng",c:"zaneprázdněný",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"Jsem velmi zaneprázdněný/á." },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"忙",p:"máng",c:"zaneprázdněný",cls:"adj"},{h:"吗",p:"ma",c:"(ot.)",cls:"particle"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Jsi zaneprázdněný/á?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"累",p:"lèi",c:"unavený",cls:"adj"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Jsem velmi unavený/á." },
      { tiles:[{h:"今",p:"jīn",c:"dnes",cls:"l1"},{h:"天",p:"tiān",c:"den",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"热",p:"rè",c:"horký",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Dnes je velmi horko!" },
      { tiles:[{h:"今",p:"jīn",c:"dnes",cls:"l1"},{h:"天",p:"tiān",c:"den",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"冷",p:"lěng",c:"studený",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"Dnes je velmi chladno." },
      { tiles:[{h:"今",p:"jīn",c:"dnes",cls:"l1"},{h:"天",p:"tiān",c:"den",cls:"l1"},{h:"天",p:"tiān",c:"počasí",cls:"l1"},{h:"气",p:"qì",c:"vzduch",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"好",p:"hǎo",c:"dobrý",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Dnes je hezké počasí!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"饿",p:"è",c:"hladový",cls:"adj"},{h:"了",p:"le",c:"(dok.)",cls:"particle"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Mám hlad!" },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"吃",p:"chī",c:"jíst",cls:"verb"},{h:"饭",p:"fàn",c:"rýže",cls:"l1"},{h:"了",p:"le",c:"(dok.)",cls:"particle"},{h:"吗",p:"ma",c:"(ot.)",cls:"particle"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Už jsi jedl/a?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"还",p:"hái",c:"ještě",cls:"adv"},{h:"没",p:"méi",c:"ne-",cls:"adv"},{h:"吃",p:"chī",c:"jíst",cls:"verb"},{h:".",p:"",c:"",cls:"punct"}], czech:"Ještě jsem nejedl/a." },
      { tiles:[{h:"这",p:"zhè",c:"toto",cls:"l1"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"菜",p:"cài",c:"jídlo",cls:"l2"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"辣",p:"là",c:"pálivý",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Toto jídlo je velmi pálivé!" },
      { tiles:[{h:"这",p:"zhè",c:"toto",cls:"l1"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"苹",p:"píng",c:"",cls:"l2"},{h:"果",p:"guǒ",c:"ovoce",cls:"l2"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"甜",p:"tián",c:"sladký",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Toto jablko je velmi sladké!" },
      { tiles:[{h:"这",p:"zhè",c:"toto",cls:"l1"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"菜",p:"cài",c:"jídlo",cls:"l2"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"苦",p:"kǔ",c:"hořký",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"Toto jídlo je hořké." },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"想",p:"xiǎng",c:"chtít",cls:"verb"},{h:"喝",p:"hē",c:"pít",cls:"verb"},{h:"水",p:"shuǐ",c:"voda",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Chci se napít vody." },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"喝",p:"hē",c:"pít",cls:"verb"},{h:"茶",p:"chá",c:"čaj",cls:"l2"},{h:"还",p:"hái",c:"nebo",cls:"adv"},{h:"是",p:"shì",c:"být",cls:"verb"},{h:"咖",p:"kā",c:"",cls:"l2"},{h:"啡",p:"fēi",c:"káva",cls:"l2"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Piješ čaj nebo kávu?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"会",p:"huì",c:"umět",cls:"verb"},{h:"说",p:"shuō",c:"mluvit",cls:"verb"},{h:"中",p:"zhōng",c:"",cls:"l1"},{h:"文",p:"wén",c:"čínsky",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Neumím čínsky." },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"在",p:"zài",c:"právě",cls:"adv"},{h:"学",p:"xué",c:"učit se",cls:"verb"},{h:"中",p:"zhōng",c:"",cls:"l1"},{h:"文",p:"wén",c:"čínsky",cls:"l1"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Právě se učím čínsky!" },
      { tiles:[{h:"中",p:"zhōng",c:"",cls:"l1"},{h:"文",p:"wén",c:"čínský",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"难",p:"nán",c:"těžký",cls:"adj"},{h:"吗",p:"ma",c:"(ot.)",cls:"particle"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Je čínština moc těžká?" },
      { tiles:[{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"难",p:"nán",c:"těžký",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"},{h:"加",p:"jiā",c:"přidat",cls:"verb"},{h:"油",p:"yóu",c:"olej",cls:"l1"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Není těžká! Nevzdávej se!" },
      { tiles:[{h:"请",p:"qǐng",c:"prosím",cls:"verb"},{h:"问",p:"wèn",c:"zeptat se",cls:"verb"},{h:"厕",p:"cè",c:"záchod",cls:"l2"},{h:"所",p:"suǒ",c:"místo",cls:"particle"},{h:"在",p:"zài",c:"být v",cls:"adv"},{h:"哪",p:"nǎ",c:"kde",cls:"l1"},{h:"里",p:"lǐ",c:"kde",cls:"l1"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Promiňte, kde jsou toalety?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"们",p:"men",c:"pl.",cls:"particle"},{h:"都",p:"dōu",c:"všichni",cls:"adv"},{h:"是",p:"shì",c:"být",cls:"verb"},{h:"学",p:"xué",c:"",cls:"l1"},{h:"生",p:"shēng",c:"student",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Všichni jsme studenti." },
      { tiles:[{h:"她",p:"tā",c:"ona",cls:"l1"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"是",p:"shì",c:"být",cls:"verb"},{h:"老",p:"lǎo",c:"starý",cls:"adj"},{h:"师",p:"shī",c:"učitel",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Ona není učitelka." },
      { tiles:[{h:"现",p:"xiàn",c:"teď",cls:"l1"},{h:"在",p:"zài",c:"teď",cls:"adv"},{h:"几",p:"jǐ",c:"kolik",cls:"l1"},{h:"点",p:"diǎn",c:"hodin",cls:"l1"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Kolik je hodin?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"去",p:"qù",c:"jít",cls:"verb"},{h:"学",p:"xué",c:"",cls:"l1"},{h:"校",p:"xiào",c:"škola",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Jdu do školy." },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"来",p:"lái",c:"přicházet",cls:"verb"},{h:"自",p:"zì",c:"od",cls:"l1"},{h:"捷",p:"jié",c:"",cls:"l2"},{h:"克",p:"kè",c:"Česko",cls:"l2"},{h:".",p:"",c:"",cls:"punct"}], czech:"Jsem z Česka." },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"来",p:"lái",c:"přicházet",cls:"verb"},{h:"自",p:"zì",c:"od",cls:"l1"},{h:"哪",p:"nǎ",c:"kde",cls:"l1"},{h:"里",p:"lǐ",c:"kde",cls:"l1"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Odkud pocházíš?" },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"喜",p:"xǐ",c:"",cls:"verb"},{h:"欢",p:"huān",c:"mít rád",cls:"verb"},{h:"中",p:"zhōng",c:"",cls:"l1"},{h:"文",p:"wén",c:"čínsky",cls:"l1"},{h:"吗",p:"ma",c:"(ot.)",cls:"particle"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Máš rád/a čínštinu?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"非",p:"fēi",c:"velmi",cls:"adv"},{h:"常",p:"cháng",c:"velmi",cls:"adv"},{h:"喜",p:"xǐ",c:"",cls:"verb"},{h:"欢",p:"huān",c:"mít rád",cls:"verb"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Mám to velmi rád/a!" },
      { tiles:[{h:"这",p:"zhè",c:"toto",cls:"l1"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"贵",p:"guì",c:"drahý",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"Toto je velmi drahé." },
      { tiles:[{h:"那",p:"nà",c:"tamto",cls:"l1"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"便",p:"pián",c:"",cls:"adj"},{h:"宜",p:"yí",c:"levný",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"Tamto je levné." },
      { tiles:[{h:"多",p:"duō",c:"kolik",cls:"adj"},{h:"少",p:"shǎo",c:"málo",cls:"adj"},{h:"钱",p:"qián",c:"peníze",cls:"l1"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Kolik to stojí?" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"想",p:"xiǎng",c:"chtít",cls:"verb"},{h:"买",p:"mǎi",c:"koupit",cls:"verb"},{h:"这",p:"zhè",c:"toto",cls:"l1"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:".",p:"",c:"",cls:"punct"}], czech:"Chci koupit toto." },
      { tiles:[{h:"能",p:"néng",c:"moci",cls:"verb"},{h:"便",p:"pián",c:"",cls:"adj"},{h:"宜",p:"yí",c:"levnější",cls:"adj"},{h:"一",p:"yī",c:"trochu",cls:"num"},{h:"点",p:"diǎn",c:"trochu",cls:"particle"},{h:"吗",p:"ma",c:"(ot.)",cls:"particle"},{h:"?",p:"",c:"",cls:"punct"}], czech:"Mohlo by to být trochu levnější?" },
      { tiles:[{h:"他",p:"tā",c:"on",cls:"l1"},{h:"说",p:"shuō",c:"říci",cls:"verb"},{h:"话",p:"huà",c:"řeč",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"快",p:"kuài",c:"rychlý",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"On mluví velmi rychle." },
      { tiles:[{h:"请",p:"qǐng",c:"prosím",cls:"verb"},{h:"说",p:"shuō",c:"říci",cls:"verb"},{h:"慢",p:"màn",c:"pomalu",cls:"adj"},{h:"一",p:"yī",c:"trochu",cls:"num"},{h:"点",p:"diǎn",c:"trochu",cls:"particle"},{h:".",p:"",c:"",cls:"punct"}], czech:"Mluvte prosím pomaleji." },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"明",p:"míng",c:"jasný",cls:"adj"},{h:"白",p:"bái",c:"bílý",cls:"l1"},{h:"了",p:"le",c:"(dok.)",cls:"particle"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Rozumím! Pochopil/a jsem!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"明",p:"míng",c:"jasný",cls:"adj"},{h:"白",p:"bái",c:"bílý",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Nerozumím." },
      { tiles:[{h:"这",p:"zhè",c:"toto",cls:"l1"},{h:"本",p:"běn",c:"kus",cls:"particle"},{h:"书",p:"shū",c:"kniha",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"有",p:"yǒu",c:"mít",cls:"verb"},{h:"趣",p:"qù",c:"zajímavý",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Tato kniha je velmi zajímavá!" },
      { tiles:[{h:"今",p:"jīn",c:"dnes",cls:"l1"},{h:"天",p:"tiān",c:"den",cls:"l1"},{h:"的",p:"de",c:"(přív.)",cls:"particle"},{h:"作",p:"zuò",c:"",cls:"l2"},{h:"业",p:"yè",c:"úkol",cls:"l2"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"难",p:"nán",c:"těžký",cls:"adj"},{h:".",p:"",c:"",cls:"punct"}], czech:"Dnešní úkol je velmi těžký." },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"说",p:"shuō",c:"říci",cls:"verb"},{h:"的",p:"de",c:"(přív.)",cls:"particle"},{h:"对",p:"duì",c:"správný",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Máš pravdu!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"同",p:"tóng",c:"stejný",cls:"adj"},{h:"意",p:"yì",c:"souhlas",cls:"l1"},{h:".",p:"",c:"",cls:"punct"}], czech:"Nesouhlasím." },
      { tiles:[{h:"你",p:"nǐ",c:"ty",cls:"l1"},{h:"走",p:"zǒu",c:"jít",cls:"verb"},{h:"得",p:"de",c:"(výsl.)",cls:"particle"},{h:"太",p:"tài",c:"příliš",cls:"adv"},{h:"慢",p:"màn",c:"pomalu",cls:"adj"},{h:"了",p:"le",c:"(dok.)",cls:"particle"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Jdeš příliš pomalu!" },
      { tiles:[{h:"百",p:"bǎi",c:"sto",cls:"num"},{h:"分",p:"fēn",c:"procent",cls:"l1"},{h:"之",p:"zhī",c:"z",cls:"particle"},{h:"百",p:"bǎi",c:"sto",cls:"num"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Stoprocentně!" },
      { tiles:[{h:"一",p:"yī",c:"jeden",cls:"num"},{h:"千",p:"qiān",c:"tisíc",cls:"num"},{h:"个",p:"gè",c:"kus",cls:"particle"},{h:"汉",p:"hàn",c:"",cls:"l1"},{h:"字",p:"zì",c:"znak",cls:"l1"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Tisíc čínských znaků!" },
      { tiles:[{h:"这",p:"zhè",c:"toto",cls:"l1"},{h:"道",p:"dào",c:"jídlo",cls:"particle"},{h:"菜",p:"cài",c:"jídlo",cls:"l2"},{h:"酸",p:"suān",c:"kyselý",cls:"adj"},{h:"甜",p:"tián",c:"sladký",cls:"adj"},{h:"苦",p:"kǔ",c:"hořký",cls:"adj"},{h:"辣",p:"là",c:"pálivý",cls:"adj"},{h:"都",p:"dōu",c:"vše",cls:"adv"},{h:"有",p:"yǒu",c:"mít",cls:"verb"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Toto jídlo má vše — kyselé, sladké, hořké i pálivé!" },
      { tiles:[{h:"因",p:"yīn",c:"příčina",cls:"conj"},{h:"为",p:"wèi",c:"kvůli",cls:"conj"},{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"很",p:"hěn",c:"velmi",cls:"adv"},{h:"忙",p:"máng",c:"zaneprázdněný",cls:"adj"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Protože jsem velmi zaneprázdněný/á." },
      { tiles:[{h:"所",p:"suǒ",c:"proto",cls:"conj"},{h:"以",p:"yǐ",c:"tedy",cls:"conj"},{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"来",p:"lái",c:"přijít",cls:"verb"},{h:"晚",p:"wǎn",c:"pozdě",cls:"adj"},{h:"了",p:"le",c:"(dok.)",cls:"particle"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Proto jsem přišel/přišla pozdě." },
      { tiles:[{h:"虽",p:"suī",c:"",cls:"conj"},{h:"然",p:"rán",c:"ačkoli",cls:"conj"},{h:"贵",p:"guì",c:"drahý",cls:"adj"},{h:",",p:"",c:"",cls:"punct"},{h:"但",p:"dàn",c:"",cls:"conj"},{h:"是",p:"shì",c:"ale",cls:"conj"},{h:"好",p:"hǎo",c:"dobrý",cls:"adj"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Ačkoli je to drahé, je to dobré." },
      { tiles:[{h:"如",p:"rú",c:"",cls:"conj"},{h:"果",p:"guǒ",c:"pokud",cls:"conj"},{h:"下",p:"xià",c:"padat",cls:"verb"},{h:"雨",p:"yǔ",c:"déšť",cls:"l1"},{h:",",p:"",c:"",cls:"punct"},{h:"就",p:"jiù",c:"pak",cls:"conj"},{h:"别",p:"bié",c:"ne-",cls:"adv"},{h:"出",p:"chū",c:"vyjít",cls:"verb"},{h:"门",p:"mén",c:"dveře",cls:"l1"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Pokud prší, nevycházej ven." },
      { tiles:[{h:"不",p:"bù",c:"ne-",cls:"adv"},{h:"但",p:"dàn",c:"jen",cls:"conj"},{h:"聪",p:"cōng",c:"",cls:"adj"},{h:"明",p:"míng",c:"chytrý",cls:"adj"},{h:",",p:"",c:"",cls:"punct"},{h:"而",p:"ér",c:"",cls:"conj"},{h:"且",p:"qiě",c:"také",cls:"conj"},{h:"勤",p:"qín",c:"",cls:"adj"},{h:"劳",p:"láo",c:"pilný",cls:"adj"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Nejenže je chytrý, ale také pilný." },
      { tiles:[{h:"他",p:"tā",c:"on",cls:"l1"},{h:"既",p:"jì",c:"jak",cls:"conj"},{h:"聪",p:"cōng",c:"",cls:"adj"},{h:"明",p:"míng",c:"chytrý",cls:"adj"},{h:"又",p:"yòu",c:"tak",cls:"conj"},{h:"帅",p:"shuài",c:"pohledný",cls:"adj"},{h:"。",p:"",c:"",cls:"punct"}], czech:"On je jak chytrý, tak i pohledný." },
      { tiles:[{h:"越",p:"yuè",c:"čím",cls:"conj"},{h:"来",p:"lái",c:"",cls:"verb"},{h:"越",p:"yuè",c:"tím",cls:"conj"},{h:"好",p:"hǎo",c:"lepší",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Čím dál, tím lépe!" },
      { tiles:[{h:"宁",p:"nìng",c:"raději",cls:"conj"},{h:"可",p:"kě",c:"raději",cls:"conj"},{h:"慢",p:"màn",c:"pomalu",cls:"adj"},{h:",",p:"",c:"",cls:"punct"},{h:"也",p:"yě",c:"také",cls:"conj"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"要",p:"yào",c:"",cls:"verb"},{h:"停",p:"tíng",c:"zastavit",cls:"verb"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Raději jdi pomalu, ale nezastav!" },
      { tiles:[{h:"一",p:"yī",c:"",cls:"conj"},{h:"边",p:"biān",c:"zatímco",cls:"conj"},{h:"学",p:"xué",c:"učit se",cls:"verb"},{h:"习",p:"xí",c:"",cls:"verb"},{h:",",p:"",c:"",cls:"punct"},{h:"一",p:"yī",c:"",cls:"conj"},{h:"边",p:"biān",c:"zároveň",cls:"conj"},{h:"听",p:"tīng",c:"poslouchat",cls:"verb"},{h:"音",p:"yīn",c:"",cls:"l1"},{h:"乐",p:"yuè",c:"hudba",cls:"l1"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Učí se a zároveň poslouchá hudbu." },
      { tiles:[{h:"无",p:"wú",c:"bez",cls:"conj"},{h:"论",p:"lùn",c:"ohledu",cls:"conj"},{h:"在",p:"zài",c:"v",cls:"adv"},{h:"哪",p:"nǎ",c:"kde",cls:"l1"},{h:"里",p:"lǐ",c:"kde",cls:"l1"},{h:",",p:"",c:"",cls:"punct"},{h:"都",p:"dōu",c:"vždy",cls:"adv"},{h:"要",p:"yào",c:"muset",cls:"verb"},{h:"努",p:"nǔ",c:"",cls:"l2"},{h:"力",p:"lì",c:"snažit se",cls:"verb"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Ať jsi kdekoliv, vždy se snaž!" },
      { tiles:[{h:"只",p:"zhǐ",c:"",cls:"conj"},{h:"要",p:"yào",c:"stačí",cls:"conj"},{h:"坚",p:"jiān",c:"",cls:"l2"},{h:"持",p:"chí",c:"vytrvat",cls:"verb"},{h:",",p:"",c:"",cls:"punct"},{h:"就",p:"jiù",c:"pak",cls:"conj"},{h:"能",p:"néng",c:"moci",cls:"verb"},{h:"成",p:"chéng",c:"",cls:"l2"},{h:"功",p:"gōng",c:"uspět",cls:"l2"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Stačí jen vytrvat a uspěješ!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"的",p:"de",c:"(přív.)",cls:"particle"},{h:"中",p:"zhōng",c:"",cls:"l1"},{h:"文",p:"wén",c:"čínština",cls:"l1"},{h:"越",p:"yuè",c:"čím",cls:"conj"},{h:"来",p:"lái",c:"",cls:"verb"},{h:"越",p:"yuè",c:"tím",cls:"conj"},{h:"好",p:"hǎo",c:"lepší",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Moje čínština je stále lepší!" },
      { tiles:[{h:"他",p:"tā",c:"on",cls:"l1"},{h:"高",p:"gāo",c:"",cls:"adj"},{h:"兴",p:"xìng",c:"šťastný",cls:"adj"},{h:"得",p:"de",c:"(výsl.)",cls:"particle"},{h:"跳",p:"tiào",c:"skákat",cls:"verb"},{h:"起",p:"qǐ",c:"vzhůru",cls:"verb"},{h:"来",p:"lái",c:"",cls:"verb"},{h:"了",p:"le",c:"(dok.)",cls:"particle"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Byl tak šťastný, že vyskočil!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"想",p:"xiǎng",c:"chtít",cls:"verb"},{h:"学",p:"xué",c:"naučit se",cls:"verb"},{h:"好",p:"hǎo",c:"dobře",cls:"adj"},{h:"中",p:"zhōng",c:"",cls:"l1"},{h:"文",p:"wén",c:"čínsky",cls:"l1"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Chci se dobře naučit čínsky!" },
      { tiles:[{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"们",p:"men",c:"pl.",cls:"particle"},{h:"的",p:"de",c:"(přív.)",cls:"particle"},{h:"中",p:"zhōng",c:"",cls:"l1"},{h:"文",p:"wén",c:"čínsky",cls:"l1"},{h:"越",p:"yuè",c:"čím",cls:"conj"},{h:"来",p:"lái",c:"",cls:"verb"},{h:"越",p:"yuè",c:"tím",cls:"conj"},{h:"好",p:"hǎo",c:"lepší",cls:"adj"},{h:"!",p:"",c:"",cls:"punct"}], czech:"Naše čínština je stále lepší!" },
      { tiles:[{h:"学",p:"xué",c:"učit",cls:"verb"},{h:"而",p:"ér",c:"a",cls:"conj"},{h:"时",p:"shí",c:"čas",cls:"l1"},{h:"习",p:"xí",c:"opakovat",cls:"verb"},{h:"之",p:"zhī",c:"to",cls:"particle"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Učit se a pravidelně opakovat. (Konfucius)" },
      { tiles:[{h:"有",p:"yǒu",c:"mít",cls:"verb"},{h:"朋",p:"péng",c:"",cls:"l1"},{h:"友",p:"yǒu",c:"přítel",cls:"l1"},{h:"自",p:"zì",c:"od",cls:"l1"},{h:"远",p:"yuǎn",c:"daleko",cls:"adj"},{h:"方",p:"fāng",c:"místo",cls:"l1"},{h:"来",p:"lái",c:"přijít",cls:"verb"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Přítel přicházející z daleka — jak příjemné! (Konfucius)" },
      { tiles:[{h:"温",p:"wēn",c:"ohřát",cls:"verb"},{h:"故",p:"gù",c:"staré",cls:"l2"},{h:"而",p:"ér",c:"a",cls:"conj"},{h:"知",p:"zhī",c:"znát",cls:"verb"},{h:"新",p:"xīn",c:"nové",cls:"adj"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Opakovat staré a poznávat nové. (Konfucius)" },
      { tiles:[{h:"三",p:"sān",c:"tři",cls:"num"},{h:"人",p:"rén",c:"lidé",cls:"l1"},{h:"行",p:"xíng",c:"jít",cls:"verb"},{h:",",p:"",c:"",cls:"punct"},{h:"必",p:"bì",c:"jistě",cls:"adv"},{h:"有",p:"yǒu",c:"mít",cls:"verb"},{h:"我",p:"wǒ",c:"já",cls:"l1"},{h:"师",p:"shī",c:"učitel",cls:"l1"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Kdykoli jsou tři lidé, jeden mi může být učitelem. (Konfucius)" },
      { tiles:[{h:"己",p:"jǐ",c:"já",cls:"l1"},{h:"所",p:"suǒ",c:"to co",cls:"particle"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"欲",p:"yù",c:"přát",cls:"verb"},{h:",",p:"",c:"",cls:"punct"},{h:"勿",p:"wù",c:"ne-",cls:"adv"},{h:"施",p:"shī",c:"dělat",cls:"verb"},{h:"于",p:"yú",c:"vůči",cls:"particle"},{h:"人",p:"rén",c:"lidé",cls:"l1"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Co sám nechceš, nečiň druhým. (Konfucius)" },
      { tiles:[{h:"路",p:"lù",c:"cesta",cls:"l2"},{h:"遥",p:"yáo",c:"daleko",cls:"adj"},{h:"知",p:"zhī",c:"poznat",cls:"verb"},{h:"马",p:"mǎ",c:"kůň",cls:"l2"},{h:"力",p:"lì",c:"síla",cls:"l1"},{h:",",p:"",c:"",cls:"punct"},{h:"日",p:"rì",c:"den",cls:"l1"},{h:"久",p:"jiǔ",c:"dlouho",cls:"adj"},{h:"见",p:"jiàn",c:"vidět",cls:"verb"},{h:"人",p:"rén",c:"člověk",cls:"l1"},{h:"心",p:"xīn",c:"srdce",cls:"l1"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Po dlouhé cestě poznáš sílu koně, časem poznáš srdce člověka." },
      { tiles:[{h:"知",p:"zhī",c:"vědět",cls:"verb"},{h:"之",p:"zhī",c:"to",cls:"particle"},{h:"为",p:"wéi",c:"je",cls:"verb"},{h:"知",p:"zhī",c:"vědět",cls:"verb"},{h:"之",p:"zhī",c:"",cls:"particle"},{h:",",p:"",c:"",cls:"punct"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"知",p:"zhī",c:"vědět",cls:"verb"},{h:"为",p:"wéi",c:"je",cls:"verb"},{h:"不",p:"bù",c:"ne",cls:"adv"},{h:"知",p:"zhī",c:"vědět",cls:"verb"},{h:"。",p:"",c:"",cls:"punct"}], czech:"Vědět, že víš, a vědět, že nevíš — to je moudrost. (Konfucius)" },
    ],

  // 📰 Authentic Modern Chinese News (Xinhua, People's Daily, CCTV)
  news: [
    {
      sourceName: "新华网 (Xinhua News)",
      sourceUrl: "http://www.news.cn/tech/",
      topic: "🚀 Kosmonautika & Věda",
      czech: "Čínský vesmírný program vypustil novou průzkumnou družici pro vesmírnou stanici.",
      tiles: [
        {h:"中",p:"zhōng",c:"střed",cls:"l1"},
        {h:"国",p:"guó",c:"země",cls:"l1"},
        {h:"航",p:"háng",c:"plavba",cls:"l2"},
        {h:"天",p:"tiān",c:"vesmír",cls:"l1"},
        {h:"发",p:"fā",c:"vyslat",cls:"verb"},
        {h:"射",p:"shè",c:"vystřelit",cls:"verb"},
        {h:"新",p:"xīn",c:"nový",cls:"adj"},
        {h:"的",p:"de",c:"(přív.)",cls:"particle"},
        {h:"空",p:"kōng",c:"prostor",cls:"l2"},
        {h:"间",p:"jiān",c:"mezi",cls:"l2"},
        {h:"站",p:"zhàn",c:"stanice",cls:"l1"},
        {h:"探",p:"tàn",c:"pátrat",cls:"verb"},
        {h:"索",p:"suǒ",c:"hledat",cls:"verb"},
        {h:"卫",p:"wèi",c:"chránit",cls:"l2"},
        {h:"星",p:"xīng",c:"hvězda",cls:"l1"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "人民日报 (People's Daily)",
      sourceUrl: "http://finance.people.com.cn/",
      topic: "🌿 Zelená energie",
      czech: "Zelená energie a technologické inovace podporují vysoce kvalitní hospodářský rozvoj.",
      tiles: [
        {h:"绿",p:"lǜ",c:"zelená",cls:"l2"},
        {h:"色",p:"sè",c:"barva",cls:"l2"},
        {h:"能",p:"néng",c:"energie",cls:"l1"},
        {h:"源",p:"yuán",c:"zdroj",cls:"l2"},
        {h:"与",p:"yǔ",c:"a",cls:"conj"},
        {h:"科",p:"kē",c:"věda",cls:"l2"},
        {h:"技",p:"jì",c:"technika",cls:"l2"},
        {h:"创",p:"chuàng",c:"tvořit",cls:"verb"},
        {h:"新",p:"xīn",c:"nový",cls:"adj"},
        {h:"推",p:"tuī",c:"tlačit",cls:"verb"},
        {h:"动",p:"dòng",c:"pohyb",cls:"verb"},
        {h:"经",p:"jīng",c:"ekonomie",cls:"l2"},
        {h:"济",p:"jì",c:"hospodářství",cls:"l2"},
        {h:"高",p:"gāo",c:"vysoká",cls:"adj"},
        {h:"质",p:"zhì",c:"kvalita",cls:"l2"},
        {h:"量",p:"liàng",c:"množství",cls:"l2"},
        {h:"发",p:"fā",c:"rozvoj",cls:"verb"},
        {h:"展",p:"zhǎn",c:"růst",cls:"verb"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "央视新闻 (CCTV News)",
      sourceUrl: "https://news.cctv.com/",
      topic: "🚅 Vysokorychlostní železnice",
      czech: "Síť vysokorychlostních vlaků činí cestování mezi městy rychlejší a pohodlnější.",
      tiles: [
        {h:"高",p:"gāo",c:"vysoký",cls:"adj"},
        {h:"铁",p:"tiě",c:"železo",cls:"l2"},
        {h:"网",p:"wǎng",c:"síť",cls:"l1"},
        {h:"络",p:"luò",c:"spojení",cls:"l2"},
        {h:"让",p:"ràng",c:"nechat",cls:"verb"},
        {h:"城",p:"chéng",c:"město",cls:"l1"},
        {h:"市",p:"shì",c:"trh",cls:"l1"},
        {h:"之",p:"zhī",c:"mezi",cls:"particle"},
        {h:"间",p:"jiān",c:"střed",cls:"l2"},
        {h:"旅",p:"lǚ",c:"cestovat",cls:"verb"},
        {h:"行",p:"xíng",c:"jízda",cls:"verb"},
        {h:"更",p:"gèng",c:"ještě",cls:"adv"},
        {h:"加",p:"jiā",c:"více",cls:"adv"},
        {h:"快",p:"kuài",c:"rychlý",cls:"adj"},
        {h:"捷",p:"jié",c:"hbitý",cls:"adj"},
        {h:"方",p:"fāng",c:"vhodný",cls:"l1"},
        {h:"便",p:"biàn",c:"pohodlný",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "中国日报 (China Daily)",
      sourceUrl: "https://cn.chinadaily.com.cn/",
      topic: "💻 Digitální ekonomika & AI",
      czech: "Digitální ekonomika a umělá inteligence přinášejí mladým lidem nové příležitosti.",
      tiles: [
        {h:"数",p:"shù",c:"číslo",cls:"num"},
        {h:"字",p:"zì",c:"znak",cls:"l1"},
        {h:"经",p:"jīng",c:"ekonomika",cls:"l2"},
        {h:"济",p:"jì",c:"",cls:"l2"},
        {h:"与",p:"yǔ",c:"a",cls:"conj"},
        {h:"人",p:"rén",c:"člověk",cls:"l1"},
        {h:"工",p:"gōng",c:"práce",cls:"l1"},
        {h:"智",p:"zhì",c:"moudrost",cls:"l2"},
        {h:"能",p:"néng",c:"schopnost",cls:"l1"},
        {h:"为",p:"wèi",c:"pro",cls:"prep"},
        {h:"年",p:"nián",c:"rok",cls:"l1"},
        {h:"轻",p:"qīng",c:"mladý",cls:"adj"},
        {h:"人",p:"rén",c:"lidé",cls:"l1"},
        {h:"带",p:"dài",c:"přinést",cls:"verb"},
        {h:"来",p:"lái",c:"přijít",cls:"verb"},
        {h:"新",p:"xīn",c:"nové",cls:"adj"},
        {h:"机",p:"jī",c:"příležitost",cls:"l1"},
        {h:"遇",p:"yù",c:"setkání",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "新华网国际 (Xinhua Global)",
      sourceUrl: "http://www.news.cn/world/",
      topic: "🤝 Mezinárodní vztahy",
      czech: "Mezinárodní kulturní výměna prohlubuje vzájemné porozumění a přátelství mezi národy.",
      tiles: [
        {h:"国",p:"guó",c:"stát",cls:"l1"},
        {h:"际",p:"jì",c:"mezinárodní",cls:"l2"},
        {h:"文",p:"wén",c:"kultura",cls:"l1"},
        {h:"化",p:"huà",c:"",cls:"l2"},
        {h:"交",p:"jiāo",c:"výměna",cls:"verb"},
        {h:"流",p:"liú",c:"proud",cls:"verb"},
        {h:"让",p:"ràng",c:"nechat",cls:"verb"},
        {h:"各",p:"gè",c:"každý",cls:"l2"},
        {h:"国",p:"guó",c:"národ",cls:"l1"},
        {h:"人",p:"rén",c:"lid",cls:"l1"},
        {h:"民",p:"mín",c:"",cls:"l1"},
        {h:"加",p:"jiā",c:"přidat",cls:"verb"},
        {h:"深",p:"shēn",c:"hloubka",cls:"adj"},
        {h:"互",p:"hù",c:"vzájemně",cls:"adv"},
        {h:"相",p:"xiāng",c:"",cls:"adv"},
        {h:"理",p:"lǐ",c:"rozumět",cls:"verb"},
        {h:"解",p:"jiě",c:"",cls:"verb"},
        {h:"与",p:"yǔ",c:"a",cls:"conj"},
        {h:"友",p:"yǒu",c:"přátelství",cls:"l1"},
        {h:"谊",p:"yì",c:"",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "光明日报 (Guangming Daily)",
      sourceUrl: "https://edu.gmw.cn/",
      topic: "🎓 Vzdělání & Inovace",
      czech: "Moderní univerzity kladou důraz na rozvoj inovativního myšlení a praktických dovedností studentů.",
      tiles: [
        {h:"现",p:"xiàn",c:"současný",cls:"l1"},
        {h:"代",p:"dài",c:"éra",cls:"l2"},
        {h:"大",p:"dà",c:"velká",cls:"adj"},
        {h:"学",p:"xué",c:"škola",cls:"verb"},
        {h:"注",p:"zhù",c:"zaměřit",cls:"verb"},
        {h:"重",p:"zhòng",c:"důraz",cls:"adj"},
        {h:"培",p:"péi",c:"pěstovat",cls:"verb"},
        {h:"养",p:"yǎng",c:"vychovat",cls:"verb"},
        {h:"学",p:"xué",c:"student",cls:"l1"},
        {h:"生",p:"shēng",c:"",cls:"l1"},
        {h:"创",p:"chuàng",c:"tvořivý",cls:"verb"},
        {h:"新",p:"xīn",c:"nový",cls:"adj"},
        {h:"思",p:"sī",c:"myslet",cls:"verb"},
        {h:"维",p:"wéi",c:"",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "人民网健康 (People's Health)",
      sourceUrl: "http://health.people.com.cn/",
      topic: "🏃 Zdravý životní styl",
      czech: "Pravidelný denní režim a přiměřený pohyb jsou základem dobrého fyzického zdraví.",
      tiles: [
        {h:"保",p:"bǎo",c:"udržet",cls:"verb"},
        {h:"持",p:"chí",c:"uchovat",cls:"verb"},
        {h:"规",p:"guī",c:"pravidlo",cls:"l2"},
        {h:"律",p:"lǜ",c:"rytmus",cls:"l2"},
        {h:"作",p:"zuò",c:"práce",cls:"verb"},
        {h:"息",p:"xī",c:"odpočinek",cls:"verb"},
        {h:"适",p:"shì",c:"přiměřený",cls:"adj"},
        {h:"度",p:"dù",c:"míra",cls:"l2"},
        {h:"运",p:"yùn",c:"pohyb",cls:"verb"},
        {h:"动",p:"dòng",c:"sport",cls:"verb"},
        {h:"身",p:"shēn",c:"tělo",cls:"l1"},
        {h:"体",p:"tǐ",c:"",cls:"l1"},
        {h:"健",p:"jiàn",c:"zdravý",cls:"adj"},
        {h:"康",p:"kāng",c:"",cls:"adj"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "科技日报 (Science Daily)",
      sourceUrl: "http://www.stdaily.com/",
      topic: "🔭 Astronomie FAST",
      czech: "Čínský teleskop FAST (Nebeské oko) objevil přes tisíc nových pulsarů.",
      tiles: [
        {h:"中",p:"zhōng",c:"střed",cls:"l1"},
        {h:"国",p:"guó",c:"země",cls:"l1"},
        {h:"天",p:"tiān",c:"nebe",cls:"l1"},
        {h:"眼",p:"yǎn",c:"oko",cls:"l1"},
        {h:"望",p:"wàng",c:"dívat se",cls:"verb"},
        {h:"远",p:"yuǎn",c:"daleko",cls:"adj"},
        {h:"镜",p:"jìng",c:"zrcadlo",cls:"l2"},
        {h:"发",p:"fā",c:"objevit",cls:"verb"},
        {h:"现",p:"xiàn",c:"",cls:"verb"},
        {h:"千",p:"qiān",c:"tisíc",cls:"num"},
        {h:"颗",p:"kē",c:"(klasif.)",cls:"particle"},
        {h:"新",p:"xīn",c:"nových",cls:"adj"},
        {h:"脉",p:"mài",c:"pulzní",cls:"l2"},
        {h:"冲",p:"chōng",c:"",cls:"l2"},
        {h:"星",p:"xīng",c:"hvězda",cls:"l1"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "央视财经 (CCTV Finance)",
      sourceUrl: "https://jingji.cctv.com/",
      topic: "🚢 Obchod & Logistika",
      czech: "Objem přepraveného zboží v mezinárodních obchodních přístavech dosáhl nového rekordu.",
      tiles: [
        {h:"国",p:"guó",c:"stát",cls:"l1"},
        {h:"际",p:"jì",c:"mezinárodní",cls:"l2"},
        {h:"贸",p:"mào",c:"obchod",cls:"l2"},
        {h:"易",p:"yì",c:"",cls:"l2"},
        {h:"港",p:"gǎng",c:"přístav",cls:"l2"},
        {h:"口",p:"kǒu",c:"ústa",cls:"l1"},
        {h:"货",p:"huò",c:"zboží",cls:"l2"},
        {h:"物",p:"wù",c:"věc",cls:"l2"},
        {h:"创",p:"chuàng",c:"vytvořit",cls:"verb"},
        {h:"新",p:"xīn",c:"nový",cls:"adj"},
        {h:"历",p:"lì",c:"historický",cls:"l2"},
        {h:"史",p:"shǐ",c:"dějiny",cls:"l2"},
        {h:"记",p:"jì",c:"záznam",cls:"verb"},
        {h:"录",p:"lù",c:"rekord",cls:"verb"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "人民网体育 (People's Sports)",
      sourceUrl: "http://sports.people.com.cn/",
      topic: "⛷️ Zimní sporty",
      czech: "Zimní sporty přitahují stále více dětí a mládeže k aktivnímu pohybu.",
      tiles: [
        {h:"冰",p:"bīng",c:"led",cls:"l2"},
        {h:"雪",p:"xuě",c:"sníh",cls:"l2"},
        {h:"运",p:"yùn",c:"sport",cls:"verb"},
        {h:"动",p:"dòng",c:"",cls:"verb"},
        {h:"吸",p:"xī",c:"přitahovat",cls:"verb"},
        {h:"引",p:"yǐn",c:"",cls:"verb"},
        {h:"青",p:"qīng",c:"mládež",cls:"l2"},
        {h:"少",p:"shào",c:"",cls:"l1"},
        {h:"年",p:"nián",c:"",cls:"l1"},
        {h:"积",p:"jī",c:"aktivně",cls:"adv"},
        {h:"极",p:"jí",c:"",cls:"adv"},
        {h:"参",p:"cān",c:"účastnit se",cls:"verb"},
        {h:"与",p:"yù",c:"",cls:"verb"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    }
  ],

  // 🏮 Chinese Culture, Traditions, Tea & Heritage
  culture: [
    {
      sourceName: "中国文化网 (China Culture)",
      sourceUrl: "http://en.chinaculture.org/",
      topic: "🍵 Čajová kultura",
      czech: "Čínský čajový obřad klade důraz na klidnou mysl, čistotu ducha a vychutnávání krásy života.",
      tiles: [
        {h:"中",p:"zhōng",c:"střed",cls:"l1"},
        {h:"国",p:"guó",c:"země",cls:"l1"},
        {h:"茶",p:"chá",c:"čaj",cls:"l1"},
        {h:"道",p:"dào",c:"cesta",cls:"l2"},
        {h:"讲",p:"jiǎng",c:"dbát na",cls:"verb"},
        {h:"究",p:"jiū",c:"zkoumat",cls:"verb"},
        {h:"心",p:"xīn",c:"srdce/mysl",cls:"l1"},
        {h:"静",p:"jìng",c:"tichý",cls:"adj"},
        {h:"神",p:"shén",c:"duch",cls:"l2"},
        {h:"清",p:"qīng",c:"čistý",cls:"adj"},
        {h:"品",p:"pǐn",c:"ochutnat",cls:"verb"},
        {h:"味",p:"wèi",c:"chuť",cls:"l2"},
        {h:"生",p:"shēng",c:"život",cls:"l1"},
        {h:"活",p:"huó",c:"",cls:"l1"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "故宫博物院 (The Palace Museum)",
      sourceUrl: "https://www.dpm.org.cn/",
      topic: "🏯 Zakázané město",
      czech: "Červené zdi a žluté tašky Zakázaného města ztělesňují velkolepost tradiční čínské architektury.",
      tiles: [
        {h:"紫",p:"zǐ",c:"purpur",cls:"l3"},
        {h:"禁",p:"jìn",c:"zakázaný",cls:"l2"},
        {h:"城",p:"chéng",c:"město",cls:"l1"},
        {h:"红",p:"hóng",c:"červená",cls:"l1"},
        {h:"墙",p:"qiáng",c:"zeď",cls:"l2"},
        {h:"黄",p:"huáng",c:"žlutá",cls:"l1"},
        {h:"瓦",p:"wǎ",c:"taška",cls:"l2"},
        {h:"体",p:"tǐ",c:"ztělesňovat",cls:"verb"},
        {h:"现",p:"xiàn",c:"",cls:"verb"},
        {h:"传",p:"chuán",c:"tradiční",cls:"l2"},
        {h:"统",p:"tǒng",c:"",cls:"l2"},
        {h:"建",p:"jiàn",c:"stavba",cls:"verb"},
        {h:"筑",p:"zhù",c:"",cls:"verb"},
        {h:"壮",p:"zhuàng",c:"velkolepý",cls:"adj"},
        {h:"丽",p:"lì",c:"krásný",cls:"adj"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "中国国家画院 (National Academy of Painting)",
      sourceUrl: "http://www.cnap.org.cn/",
      topic: "✍️ Kaligrafie KaiTi",
      czech: "Úhledné a vyvážené tahy písma KaiTi jsou základem pro studium čínské kaligrafie.",
      tiles: [
        {h:"楷",p:"kǎi",c:"vzor",cls:"l3"},
        {h:"书",p:"shū",c:"písmo",cls:"l1"},
        {h:"笔",p:"bǐ",c:"štětec",cls:"l1"},
        {h:"画",p:"huà",c:"tah",cls:"verb"},
        {h:"端",p:"duān",c:"přímý",cls:"adj"},
        {h:"庄",p:"zhuāng",c:"důstojný",cls:"adj"},
        {h:"练",p:"liàn",c:"cvičit",cls:"verb"},
        {h:"习",p:"xí",c:"opakovat",cls:"verb"},
        {h:"汉",p:"hàn",c:"čínské",cls:"l1"},
        {h:"字",p:"zì",c:"znaky",cls:"l1"},
        {h:"书",p:"shū",c:"kaligrafie",cls:"l1"},
        {h:"法",p:"fǎ",c:"metoda",cls:"l1"},
        {h:"基",p:"jī",c:"základ",cls:"l2"},
        {h:"础",p:"chǔ",c:"",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "中国传统节日网 (Traditional Festivals)",
      sourceUrl: "http://www.chinaculture.org/",
      topic: "🥮 Svátek středu podzimu",
      czech: "Během svátku středu podzimu se rodina schází k obdivování úplňku a ochutnávání měsíčních koláčků.",
      tiles: [
        {h:"中",p:"zhōng",c:"střed",cls:"l1"},
        {h:"秋",p:"qiū",c:"podzim",cls:"l2"},
        {h:"节",p:"jié",c:"svátek",cls:"l1"},
        {h:"全",p:"quán",c:"celá",cls:"adj"},
        {h:"家",p:"jiā",c:"rodina",cls:"l1"},
        {h:"团",p:"tuán",c:"shledání",cls:"verb"},
        {h:"聚",p:"jù",c:"",cls:"verb"},
        {h:"赏",p:"shǎng",c:"obdivovat",cls:"verb"},
        {h:"明",p:"míng",c:"jasný",cls:"adj"},
        {h:"月",p:"yuè",c:"měsíc",cls:"l1"},
        {h:"品",p:"pǐn",c:"ochutnat",cls:"verb"},
        {h:"尝",p:"cháng",c:"",cls:"verb"},
        {h:"月",p:"yuè",c:"měsíční",cls:"l1"},
        {h:"饼",p:"bǐng",c:"koláček",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "人民网文化 (People's Daily Culture)",
      sourceUrl: "http://culture.people.com.cn/",
      topic: "🧨 Svátek jara (Nový rok)",
      czech: "O novoroční noci lepíme verše a jíme taštičky jiaozi na rozloučení se starým rokem a přivítání štěstí.",
      tiles: [
        {h:"除",p:"chú",c:"odstranit",cls:"verb"},
        {h:"夕",p:"xī",c:"večer",cls:"l2"},
        {h:"之",p:"zhī",c:"(přív.)",cls:"particle"},
        {h:"夜",p:"yè",c:"noc",cls:"l2"},
        {h:"贴",p:"tiē",c:"lepit",cls:"verb"},
        {h:"春",p:"chūn",c:"jaro",cls:"l2"},
        {h:"联",p:"lián",c:"verše",cls:"l2"},
        {h:"吃",p:"chī",c:"jíst",cls:"verb"},
        {h:"饺",p:"jiǎo",c:"taštičky",cls:"l2"},
        {h:"子",p:"zi",c:"",cls:"l1"},
        {h:"辞",p:"cí",c:"loučit se",cls:"verb"},
        {h:"旧",p:"jiù",c:"starý",cls:"adj"},
        {h:"迎",p:"yíng",c:"vítat",cls:"verb"},
        {h:"新",p:"xīn",c:"nový",cls:"adj"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "中国长城学会 (Great Wall Society)",
      sourceUrl: "http://www.greatwall.org.cn/",
      topic: "🧱 Velká čínská zeď",
      czech: "Velká čínská zeď vinoucí se horskými hřebeny je svědkem tisícileté dramatické historie.",
      tiles: [
        {h:"万",p:"wàn",c:"deset tisíc",cls:"num"},
        {h:"里",p:"lǐ",c:"míle",cls:"l1"},
        {h:"长",p:"cháng",c:"dlouhá",cls:"adj"},
        {h:"城",p:"chéng",c:"zeď",cls:"l1"},
        {h:"蜿",p:"wān",c:"vinout se",cls:"verb"},
        {h:"蜒",p:"yán",c:"",cls:"verb"},
        {h:"群",p:"qún",c:"skupina",cls:"l2"},
        {h:"山",p:"shān",c:"hory",cls:"l1"},
        {h:"见",p:"jiàn",c:"vidět",cls:"verb"},
        {h:"证",p:"zhèng",c:"svědčit",cls:"verb"},
        {h:"千",p:"qiān",c:"tisíc",cls:"num"},
        {h:"年",p:"nián",c:"let",cls:"l1"},
        {h:"历",p:"lì",c:"historie",cls:"l2"},
        {h:"史",p:"shǐ",c:"",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "中国社会科学院 (CASS History)",
      sourceUrl: "http://lsxy.cass.cn/",
      topic: "🐫 Hedvábná stezka",
      czech: "Starověká Hedvábná stezka podpořila obchodní i kulturní propojení východní a západní civilizace.",
      tiles: [
        {h:"古",p:"gǔ",c:"starý",cls:"adj"},
        {h:"代",p:"dài",c:"éra",cls:"l2"},
        {h:"丝",p:"sī",c:"hedvábí",cls:"l2"},
        {h:"绸",p:"chóu",c:"",cls:"l2"},
        {h:"之",p:"zhī",c:"(přív.)",cls:"particle"},
        {h:"路",p:"lù",c:"cesta",cls:"l2"},
        {h:"促",p:"cù",c:"podpořit",cls:"verb"},
        {h:"进",p:"jìn",c:"vpřed",cls:"verb"},
        {h:"东",p:"dōng",c:"východ",cls:"l1"},
        {h:"西",p:"xī",c:"západ",cls:"l1"},
        {h:"文",p:"wén",c:"kultura",cls:"l1"},
        {h:"明",p:"míng",c:"jasná",cls:"adj"},
        {h:"交",p:"jiāo",c:"propojení",cls:"verb"},
        {h:"融",p:"róng",c:"",cls:"verb"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "中国中医科学院 (Chinese Medical Sciences)",
      sourceUrl: "http://www.cacms.ac.cn/",
      topic: "🌿 Tradiční čínská medicína",
      czech: "Tradiční čínská medicína klade důraz na rovnováhu jin-jang a harmonii člověka s přírodou.",
      tiles: [
        {h:"中",p:"zhōng",c:"čínská",cls:"l1"},
        {h:"医",p:"yī",c:"medicína",cls:"l1"},
        {h:"注",p:"zhù",c:"klást",cls:"verb"},
        {h:"重",p:"zhòng",c:"důraz",cls:"adj"},
        {h:"阴",p:"yīn",c:"jin",cls:"l2"},
        {h:"阳",p:"yáng",c:"jang",cls:"l2"},
        {h:"平",p:"píng",c:"rovnováha",cls:"adj"},
        {h:"衡",p:"héng",c:"",cls:"adj"},
        {h:"天",p:"tiān",c:"příroda",cls:"l1"},
        {h:"人",p:"rén",c:"člověk",cls:"l1"},
        {h:"合",p:"hé",c:"jednota",cls:"verb"},
        {h:"一",p:"yī",c:"",cls:"num"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "中国非物质文化遗产网 (UNESCO Heritage)",
      sourceUrl: "http://www.ihchina.cn/",
      topic: "🎵 Citera Guqin",
      czech: "Hluboký a tichý tón citery Guqin je zařazen na seznam nehmotného dědictví lidstva.",
      tiles: [
        {h:"古",p:"gǔ",c:"stará",cls:"adj"},
        {h:"琴",p:"qín",c:"citera",cls:"l2"},
        {h:"音",p:"yīn",c:"tón",cls:"l1"},
        {h:"色",p:"sè",c:"barva",cls:"l2"},
        {h:"深",p:"shēn",c:"hluboký",cls:"adj"},
        {h:"沉",p:"chén",c:"klidný",cls:"adj"},
        {h:"悠",p:"yōu",c:"vzdálený",cls:"adj"},
        {h:"远",p:"yuǎn",c:"",cls:"adj"},
        {h:"文",p:"wén",c:"kultura",cls:"l1"},
        {h:"化",p:"huà",c:"",cls:"l2"},
        {h:"遗",p:"yí",c:"dědictví",cls:"l2"},
        {h:"产",p:"chǎn",c:"",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "故宫博物院陶瓷馆 (Palace Museum Ceramics)",
      sourceUrl: "https://www.dpm.org.cn/explore/collections/12.html",
      topic: "🏺 Modrobílý porcelán",
      czech: "Modrobílý porcelán s elegantním leskem představuje vrchol čínského keramického umění.",
      tiles: [
        {h:"青",p:"qīng",c:"modrá",cls:"l2"},
        {h:"花",p:"huā",c:"květ",cls:"l1"},
        {h:"瓷",p:"cí",c:"porcelán",cls:"l2"},
        {h:"色",p:"sè",c:"odstín",cls:"l2"},
        {h:"泽",p:"zé",c:"lesk",cls:"l2"},
        {h:"典",p:"diǎn",c:"vznešený",cls:"adj"},
        {h:"雅",p:"yǎ",c:"elegantní",cls:"adj"},
        {h:"制",p:"zhì",c:"výroba",cls:"verb"},
        {h:"瓷",p:"cí",c:"keramika",cls:"l2"},
        {h:"工",p:"gōng",c:"umění",cls:"l1"},
        {h:"艺",p:"yì",c:"",cls:"l2"},
        {h:"之",p:"zhī",c:"(přív.)",cls:"particle"},
        {h:"巅",p:"diān",c:"vrchol",cls:"l2"},
        {h:"峰",p:"fēng",c:"",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    }
  ],

  // 📖 Classical Wisdom, Literature & Chengyu Idioms
  chengyu: [
    {
      sourceName: "《庄子·秋水》Zhuangzi Classic",
      sourceUrl: "https://ctext.org/zhuangzi/floods-of-autumn",
      topic: "🐸 井底之蛙 (Žába na dně studny)",
      czech: "Žába na dně studny vidí jen úzký kruh nebe – teprve otevřená mysl pozná velikost světa.",
      tiles: [
        {h:"井",p:"jǐng",c:"studna",cls:"l2"},
        {h:"底",p:"dǐ",c:"dno",cls:"l2"},
        {h:"之",p:"zhī",c:"(přív.)",cls:"particle"},
        {h:"蛙",p:"wā",c:"žába",cls:"l3"},
        {h:"只",p:"zhǐ",c:"jen",cls:"adv"},
        {h:"见",p:"jiàn",c:"vidět",cls:"verb"},
        {h:"小",p:"xiǎo",c:"malé",cls:"adj"},
        {h:"天",p:"tiān",c:"nebe",cls:"l1"},
        {h:"开",p:"kāi",c:"otevřít",cls:"verb"},
        {h:"阔",p:"kuò",c:"široký",cls:"adj"},
        {h:"眼",p:"yǎn",c:"zrak",cls:"l1"},
        {h:"界",p:"jiè",c:"obzor",cls:"l1"},
        {h:"方",p:"fāng",c:"teprve",cls:"adv"},
        {h:"知",p:"zhī",c:"poznat",cls:"verb"},
        {h:"大",p:"dà",c:"velký",cls:"adj"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《韩非子·五蠹》Han Feizi",
      sourceUrl: "https://ctext.org/hanfeizi/wu-du",
      topic: "🐇 守株待兔 (Čekat u pařezu na zajíce)",
      czech: "Čekáním u pařezu králíka nechytíš – jen poctivá práce přináší opravdové výsledky.",
      tiles: [
        {h:"守",p:"shǒu",c:"střežit",cls:"verb"},
        {h:"株",p:"zhū",c:"pařez",cls:"l2"},
        {h:"待",p:"dài",c:"čekat",cls:"verb"},
        {h:"兔",p:"tù",c:"králík",cls:"l3"},
        {h:"难",p:"nán",c:"těžko",cls:"adj"},
        {h:"获",p:"huò",c:"získat",cls:"verb"},
        {h:"成",p:"chéng",c:"úspěch",cls:"l2"},
        {h:"功",p:"gōng",c:"",cls:"l2"},
        {h:"辛",p:"xīn",c:"namáhavý",cls:"adj"},
        {h:"勤",p:"qín",c:"pilný",cls:"adj"},
        {h:"努",p:"nǔ",c:"úsilí",cls:"l2"},
        {h:"力",p:"lì",c:"síla",cls:"l1"},
        {h:"方",p:"fāng",c:"teprve",cls:"adv"},
        {h:"有",p:"yǒu",c:"mít",cls:"verb"},
        {h:"收",p:"shōu",c:"sklizeň",cls:"verb"},
        {h:"获",p:"huò",c:"",cls:"verb"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《孟子·公孙丑上》Mengzi (Mencius)",
      sourceUrl: "https://ctext.org/mengzi/gong-sun-chou-i",
      topic: "🌱 拔苗助长 (Urychlovat růst sazenic)",
      czech: "Učení je jako růst rostlin – ukvapené urychlování věcem jen uškodí.",
      tiles: [
        {h:"拔",p:"bá",c:"vytahovat",cls:"verb"},
        {h:"苗",p:"miáo",c:"sazenice",cls:"l2"},
        {h:"助",p:"zhù",c:"pomáhat",cls:"verb"},
        {h:"长",p:"zhǎng",c:"růst",cls:"verb"},
        {h:"急",p:"jí",c:"spěchat",cls:"adj"},
        {h:"于",p:"yú",c:"na",cls:"particle"},
        {h:"求",p:"qiú",c:"usilovat",cls:"verb"},
        {h:"成",p:"chéng",c:"úspěch",cls:"l2"},
        {h:"反",p:"fǎn",c:"naopak",cls:"adv"},
        {h:"而",p:"ér",c:"však",cls:"conj"},
        {h:"有",p:"yǒu",c:"mít",cls:"verb"},
        {h:"害",p:"hài",c:"škoda",cls:"l2"},
        {h:"无",p:"wú",c:"bez",cls:"adv"},
        {h:"益",p:"yì",c:"užitek",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《淮南子·人间训》Huainanzi",
      sourceUrl: "https://ctext.org/huainanzi/ren-jian-xun",
      topic: "🐎 塞翁失马 (Štěstí v neštěstí)",
      czech: "Vše zlé je k něčemu dobré – i v těžkostech se často skrývá nová příležitost.",
      tiles: [
        {h:"塞",p:"sài",c:"hranice",cls:"l2"},
        {h:"翁",p:"wēng",c:"stařík",cls:"l2"},
        {h:"失",p:"shī",c:"ztratit",cls:"verb"},
        {h:"马",p:"mǎ",c:"kůň",cls:"l2"},
        {h:"焉",p:"yān",c:"jak",cls:"adv"},
        {h:"知",p:"zhī",c:"vědět",cls:"verb"},
        {h:"非",p:"fēi",c:"ne",cls:"adv"},
        {h:"福",p:"fú",c:"štěstí",cls:"l2"},
        {h:"逆",p:"nì",c:"protivenství",cls:"adj"},
        {h:"境",p:"jìng",c:"stav",cls:"l2"},
        {h:"往",p:"wǎng",c:"často",cls:"adv"},
        {h:"往",p:"wǎng",c:"",cls:"adv"},
        {h:"有",p:"yǒu",c:"mít",cls:"verb"},
        {h:"转",p:"zhuǎn",c:"obrat",cls:"verb"},
        {h:"机",p:"jī",c:"šance",cls:"l1"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《战国策·齐策》Warring States Intrigues",
      sourceUrl: "https://ctext.org/zhan-guo-ce/qi-er",
      topic: "🐍 画蛇添足 (Přimalovávat hadovi nohy)",
      czech: "Stačí udělat věc akorát – přidávat zbytečnosti navíc celou věc jen pokazí.",
      tiles: [
        {h:"画",p:"huà",c:"malovat",cls:"verb"},
        {h:"蛇",p:"shé",c:"had",cls:"l2"},
        {h:"添",p:"tiān",c:"přidat",cls:"verb"},
        {h:"足",p:"zú",c:"nohy",cls:"l2"},
        {h:"做",p:"zuò",c:"dělat",cls:"verb"},
        {h:"事",p:"shì",c:"věc",cls:"l1"},
        {h:"恰",p:"qià",c:"akorát",cls:"adv"},
        {h:"到",p:"dào",c:"dospět",cls:"verb"},
        {h:"好",p:"hǎo",c:"dobře",cls:"adj"},
        {h:"处",p:"chù",c:"místo",cls:"l1"},
        {h:"多",p:"duō",c:"více",cls:"adj"},
        {h:"此",p:"cǐ",c:"tento",cls:"l2"},
        {h:"一",p:"yī",c:"jeden",cls:"num"},
        {h:"举",p:"jǔ",c:"čin",cls:"verb"},
        {h:"反",p:"fǎn",c:"naopak",cls:"adv"},
        {h:"坏",p:"huài",c:"zkazit",cls:"adj"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《吕氏春秋·自知》Lüshi Chunqiu",
      sourceUrl: "https://ctext.org/lv-shi-chun-qiu/zi-zhi",
      topic: "🔔 掩耳盗铃 (Zacpávat si uši)",
      czech: "Zacpávat si uši a kradnout zvon je klamání sebe sama – problém je třeba řešit přímo.",
      tiles: [
        {h:"掩",p:"yǎn",c:"zakrýt",cls:"verb"},
        {h:"耳",p:"ěr",c:"uši",cls:"l1"},
        {h:"盗",p:"dào",c:"krást",cls:"verb"},
        {h:"铃",p:"líng",c:"zvon",cls:"l2"},
        {h:"自",p:"zì",c:"sám",cls:"l1"},
        {h:"欺",p:"qī",c:"klam",cls:"verb"},
        {h:"欺",p:"qī",c:"klamat",cls:"verb"},
        {h:"人",p:"rén",c:"lidi",cls:"l1"},
        {h:"正",p:"zhèng",c:"přímo",cls:"adj"},
        {h:"视",p:"shì",c:"pohlédnout",cls:"verb"},
        {h:"问",p:"wèn",c:"otázka",cls:"verb"},
        {h:"题",p:"tí",c:"téma",cls:"l2"},
        {h:"方",p:"fāng",c:"teprve",cls:"adv"},
        {h:"可",p:"kě",c:"lze",cls:"verb"},
        {h:"解",p:"jiě",c:"vyřešit",cls:"verb"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《论语·学而》Analects of Confucius",
      sourceUrl: "https://ctext.org/analects/xue-er",
      topic: "📜 学而时习之 (Učit se a opakovat)",
      czech: "Učit se a v pravý čas si opakovat – cožpak to nepřináší radost?",
      tiles: [
        {h:"学",p:"xué",c:"učit se",cls:"verb"},
        {h:"而",p:"ér",c:"a",cls:"conj"},
        {h:"时",p:"shí",c:"včas",cls:"l1"},
        {h:"习",p:"xí",c:"opakovat",cls:"verb"},
        {h:"之",p:"zhī",c:"to",cls:"particle"},
        {h:"不",p:"bù",c:"ne-",cls:"adv"},
        {h:"亦",p:"yì",c:"rovněž",cls:"adv"},
        {h:"说",p:"yuè",c:"radostný",cls:"adj"},
        {h:"乎",p:"hū",c:"(táz.)",cls:"particle"},
        {h:"！",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《论语·为政》Analects of Confucius",
      sourceUrl: "https://ctext.org/analects/wei-zheng",
      topic: "✨ 温故而知新 (Oživovat staré, znát nové)",
      czech: "Kdo oživuje staré a poznává nové, může být učitelem a průvodcem.",
      tiles: [
        {h:"温",p:"wēn",c:"oživovat",cls:"verb"},
        {h:"故",p:"gù",c:"staré",cls:"l2"},
        {h:"而",p:"ér",c:"a",cls:"conj"},
        {h:"知",p:"zhī",c:"poznat",cls:"verb"},
        {h:"新",p:"xīn",c:"nové",cls:"adj"},
        {h:"可",p:"kě",c:"moci",cls:"verb"},
        {h:"以",p:"yǐ",c:"jako",cls:"prep"},
        {h:"为",p:"wéi",c:"být",cls:"verb"},
        {h:"师",p:"shī",c:"učitel",cls:"l1"},
        {h:"矣",p:"yǐ",c:"(dok.)",cls:"particle"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "《汉书·枚乘传》Book of Han",
      sourceUrl: "https://ctext.org/han-shu/mei-sheng-zhuan",
      topic: "💧 水滴石穿 (Kapka vody provrtá kámen)",
      czech: "I kapka vody provrtá kámen – vytrvalost a trpělivost jsou klíčem k vrcholům poznání.",
      tiles: [
        {h:"水",p:"shuǐ",c:"voda",cls:"l1"},
        {h:"滴",p:"dī",c:"kapka",cls:"l2"},
        {h:"石",p:"shí",c:"kámen",cls:"l1"},
        {h:"穿",p:"chuān",c:"provrtat",cls:"verb"},
        {h:"持",p:"chí",c:"držet",cls:"verb"},
        {h:"之",p:"zhī",c:"to",cls:"particle"},
        {h:"以",p:"yǐ",c:"s",cls:"prep"},
        {h:"恒",p:"héng",c:"vytrvalost",cls:"adj"},
        {h:"终",p:"zhōng",c:"nakonec",cls:"adv"},
        {h:"能",p:"néng",c:"dokázat",cls:"verb"},
        {h:"攀",p:"pān",c:"vystoupat",cls:"verb"},
        {h:"登",p:"dēng",c:"",cls:"verb"},
        {h:"高",p:"gāo",c:"vysoký",cls:"adj"},
        {h:"峰",p:"fēng",c:"vrchol",cls:"l2"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    },
    {
      sourceName: "苏轼《文与可画偃竹记》Su Shi Classic",
      sourceUrl: "https://ctext.org/",
      topic: "🎋 胸有成竹 (Mít jasný plán v srdci)",
      czech: "Být předem dobře připravený a mít jasnou vizi umožňuje zvládnout každou situaci.",
      tiles: [
        {h:"胸",p:"xiōng",c:"hruď/srdce",cls:"l2"},
        {h:"有",p:"yǒu",c:"mít",cls:"verb"},
        {h:"成",p:"chéng",c:"hotový",cls:"adj"},
        {h:"竹",p:"zhú",c:"bambus",cls:"l2"},
        {h:"处",p:"chǔ",c:"čelit",cls:"verb"},
        {h:"事",p:"shì",c:"situace",cls:"l1"},
        {h:"从",p:"cóng",c:"klidný",cls:"adj"},
        {h:"容",p:"róng",c:"",cls:"adj"},
        {h:"不",p:"bù",c:"ne",cls:"adv"},
        {h:"慌",p:"huāng",c:"panikařit",cls:"verb"},
        {h:"。",p:"",c:"",cls:"punct"}
      ]
    }
  ]
};

// Build the combined 'all' collection
window.SENTENCE_COLLECTIONS.all = [
  ...window.SENTENCE_COLLECTIONS.news,
  ...window.SENTENCE_COLLECTIONS.culture,
  ...window.SENTENCE_COLLECTIONS.chengyu,
  ...window.SENTENCE_COLLECTIONS.course
];
